// Code generated by ent, DO NOT EDIT.

package reconciliationexception

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/payment/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldID, id))
}

// ReconciliationID applies equality check predicate on the "reconciliation_id" field. It's identical to ReconciliationIDEQ.
func ReconciliationID(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldReconciliationID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldOrderID, v))
}

// PlatformOrderID applies equality check predicate on the "platform_order_id" field. It's identical to PlatformOrderIDEQ.
func PlatformOrderID(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldPlatformOrderID, v))
}

// SystemAmount applies equality check predicate on the "system_amount" field. It's identical to SystemAmountEQ.
func SystemAmount(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldSystemAmount, v))
}

// PlatformAmount applies equality check predicate on the "platform_amount" field. It's identical to PlatformAmountEQ.
func PlatformAmount(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldPlatformAmount, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldReason, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldAction, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldRemark, v))
}

// HandledAt applies equality check predicate on the "handled_at" field. It's identical to HandledAtEQ.
func HandledAt(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldHandledAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReconciliationIDEQ applies the EQ predicate on the "reconciliation_id" field.
func ReconciliationIDEQ(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldReconciliationID, v))
}

// ReconciliationIDNEQ applies the NEQ predicate on the "reconciliation_id" field.
func ReconciliationIDNEQ(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldReconciliationID, v))
}

// ReconciliationIDIn applies the In predicate on the "reconciliation_id" field.
func ReconciliationIDIn(vs ...uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldReconciliationID, vs...))
}

// ReconciliationIDNotIn applies the NotIn predicate on the "reconciliation_id" field.
func ReconciliationIDNotIn(vs ...uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldReconciliationID, vs...))
}

// ReconciliationIDGT applies the GT predicate on the "reconciliation_id" field.
func ReconciliationIDGT(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldReconciliationID, v))
}

// ReconciliationIDGTE applies the GTE predicate on the "reconciliation_id" field.
func ReconciliationIDGTE(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldReconciliationID, v))
}

// ReconciliationIDLT applies the LT predicate on the "reconciliation_id" field.
func ReconciliationIDLT(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldReconciliationID, v))
}

// ReconciliationIDLTE applies the LTE predicate on the "reconciliation_id" field.
func ReconciliationIDLTE(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldReconciliationID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v uuid.UUID) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldOrderID, v))
}

// PlatformOrderIDEQ applies the EQ predicate on the "platform_order_id" field.
func PlatformOrderIDEQ(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldPlatformOrderID, v))
}

// PlatformOrderIDNEQ applies the NEQ predicate on the "platform_order_id" field.
func PlatformOrderIDNEQ(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldPlatformOrderID, v))
}

// PlatformOrderIDIn applies the In predicate on the "platform_order_id" field.
func PlatformOrderIDIn(vs ...string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldPlatformOrderID, vs...))
}

// PlatformOrderIDNotIn applies the NotIn predicate on the "platform_order_id" field.
func PlatformOrderIDNotIn(vs ...string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldPlatformOrderID, vs...))
}

// PlatformOrderIDGT applies the GT predicate on the "platform_order_id" field.
func PlatformOrderIDGT(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldPlatformOrderID, v))
}

// PlatformOrderIDGTE applies the GTE predicate on the "platform_order_id" field.
func PlatformOrderIDGTE(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldPlatformOrderID, v))
}

// PlatformOrderIDLT applies the LT predicate on the "platform_order_id" field.
func PlatformOrderIDLT(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldPlatformOrderID, v))
}

// PlatformOrderIDLTE applies the LTE predicate on the "platform_order_id" field.
func PlatformOrderIDLTE(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldPlatformOrderID, v))
}

// PlatformOrderIDContains applies the Contains predicate on the "platform_order_id" field.
func PlatformOrderIDContains(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldContains(FieldPlatformOrderID, v))
}

// PlatformOrderIDHasPrefix applies the HasPrefix predicate on the "platform_order_id" field.
func PlatformOrderIDHasPrefix(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldHasPrefix(FieldPlatformOrderID, v))
}

// PlatformOrderIDHasSuffix applies the HasSuffix predicate on the "platform_order_id" field.
func PlatformOrderIDHasSuffix(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldHasSuffix(FieldPlatformOrderID, v))
}

// PlatformOrderIDIsNil applies the IsNil predicate on the "platform_order_id" field.
func PlatformOrderIDIsNil() predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIsNull(FieldPlatformOrderID))
}

// PlatformOrderIDNotNil applies the NotNil predicate on the "platform_order_id" field.
func PlatformOrderIDNotNil() predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotNull(FieldPlatformOrderID))
}

// PlatformOrderIDEqualFold applies the EqualFold predicate on the "platform_order_id" field.
func PlatformOrderIDEqualFold(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEqualFold(FieldPlatformOrderID, v))
}

// PlatformOrderIDContainsFold applies the ContainsFold predicate on the "platform_order_id" field.
func PlatformOrderIDContainsFold(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldContainsFold(FieldPlatformOrderID, v))
}

// SystemAmountEQ applies the EQ predicate on the "system_amount" field.
func SystemAmountEQ(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldSystemAmount, v))
}

// SystemAmountNEQ applies the NEQ predicate on the "system_amount" field.
func SystemAmountNEQ(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldSystemAmount, v))
}

// SystemAmountIn applies the In predicate on the "system_amount" field.
func SystemAmountIn(vs ...float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldSystemAmount, vs...))
}

// SystemAmountNotIn applies the NotIn predicate on the "system_amount" field.
func SystemAmountNotIn(vs ...float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldSystemAmount, vs...))
}

// SystemAmountGT applies the GT predicate on the "system_amount" field.
func SystemAmountGT(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldSystemAmount, v))
}

// SystemAmountGTE applies the GTE predicate on the "system_amount" field.
func SystemAmountGTE(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldSystemAmount, v))
}

// SystemAmountLT applies the LT predicate on the "system_amount" field.
func SystemAmountLT(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldSystemAmount, v))
}

// SystemAmountLTE applies the LTE predicate on the "system_amount" field.
func SystemAmountLTE(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldSystemAmount, v))
}

// PlatformAmountEQ applies the EQ predicate on the "platform_amount" field.
func PlatformAmountEQ(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldPlatformAmount, v))
}

// PlatformAmountNEQ applies the NEQ predicate on the "platform_amount" field.
func PlatformAmountNEQ(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldPlatformAmount, v))
}

// PlatformAmountIn applies the In predicate on the "platform_amount" field.
func PlatformAmountIn(vs ...float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldPlatformAmount, vs...))
}

// PlatformAmountNotIn applies the NotIn predicate on the "platform_amount" field.
func PlatformAmountNotIn(vs ...float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldPlatformAmount, vs...))
}

// PlatformAmountGT applies the GT predicate on the "platform_amount" field.
func PlatformAmountGT(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldPlatformAmount, v))
}

// PlatformAmountGTE applies the GTE predicate on the "platform_amount" field.
func PlatformAmountGTE(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldPlatformAmount, v))
}

// PlatformAmountLT applies the LT predicate on the "platform_amount" field.
func PlatformAmountLT(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldPlatformAmount, v))
}

// PlatformAmountLTE applies the LTE predicate on the "platform_amount" field.
func PlatformAmountLTE(v float64) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldPlatformAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldStatus, vs...))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldContainsFold(FieldReason, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldHasSuffix(FieldAction, v))
}

// ActionIsNil applies the IsNil predicate on the "action" field.
func ActionIsNil() predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIsNull(FieldAction))
}

// ActionNotNil applies the NotNil predicate on the "action" field.
func ActionNotNil() predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotNull(FieldAction))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldContainsFold(FieldAction, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldContainsFold(FieldRemark, v))
}

// HandledAtEQ applies the EQ predicate on the "handled_at" field.
func HandledAtEQ(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldHandledAt, v))
}

// HandledAtNEQ applies the NEQ predicate on the "handled_at" field.
func HandledAtNEQ(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldHandledAt, v))
}

// HandledAtIn applies the In predicate on the "handled_at" field.
func HandledAtIn(vs ...time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldHandledAt, vs...))
}

// HandledAtNotIn applies the NotIn predicate on the "handled_at" field.
func HandledAtNotIn(vs ...time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldHandledAt, vs...))
}

// HandledAtGT applies the GT predicate on the "handled_at" field.
func HandledAtGT(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldHandledAt, v))
}

// HandledAtGTE applies the GTE predicate on the "handled_at" field.
func HandledAtGTE(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldHandledAt, v))
}

// HandledAtLT applies the LT predicate on the "handled_at" field.
func HandledAtLT(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldHandledAt, v))
}

// HandledAtLTE applies the LTE predicate on the "handled_at" field.
func HandledAtLTE(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldHandledAt, v))
}

// HandledAtIsNil applies the IsNil predicate on the "handled_at" field.
func HandledAtIsNil() predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIsNull(FieldHandledAt))
}

// HandledAtNotNil applies the NotNil predicate on the "handled_at" field.
func HandledAtNotNil() predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotNull(FieldHandledAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReconciliationException) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReconciliationException) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReconciliationException) predicate.ReconciliationException {
	return predicate.ReconciliationException(sql.NotPredicates(p))
}
