# Build stage
FROM golang:1.19-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o device cmd/device/main.go

# Run stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/device .
COPY configs/device.yaml configs/device.yaml

EXPOSE 8005

CMD ["./device", "-conf", "configs/device.yaml"]
