# Build stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git make protobuf

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/payment-svc ./cmd/payment-svc

# Final stage
FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /app/payment-svc .
COPY configs/payment.yaml /app/configs/payment.yaml

EXPOSE 8003

CMD ["./payment-svc"]
