# Build stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git make protobuf

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/admin-svc ./cmd/admin-svc

# Final stage
FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /app/admin-svc .
COPY configs/admin.yaml /app/configs/admin.yaml

EXPOSE 8004

CMD ["./admin-svc"]
