// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/payment/data/ent/reconciliation"
)

// ReconciliationCreate is the builder for creating a Reconciliation entity.
type ReconciliationCreate struct {
	config
	mutation *ReconciliationMutation
	hooks    []Hook
}

// SetDate sets the "date" field.
func (_c *ReconciliationCreate) SetDate(v string) *ReconciliationCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetPayMethod sets the "pay_method" field.
func (_c *ReconciliationCreate) SetPayMethod(v reconciliation.PayMethod) *ReconciliationCreate {
	_c.mutation.SetPayMethod(v)
	return _c
}

// SetNillablePayMethod sets the "pay_method" field if the given value is not nil.
func (_c *ReconciliationCreate) SetNillablePayMethod(v *reconciliation.PayMethod) *ReconciliationCreate {
	if v != nil {
		_c.SetPayMethod(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReconciliationCreate) SetStatus(v reconciliation.Status) *ReconciliationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReconciliationCreate) SetNillableStatus(v *reconciliation.Status) *ReconciliationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalOrders sets the "total_orders" field.
func (_c *ReconciliationCreate) SetTotalOrders(v int) *ReconciliationCreate {
	_c.mutation.SetTotalOrders(v)
	return _c
}

// SetNillableTotalOrders sets the "total_orders" field if the given value is not nil.
func (_c *ReconciliationCreate) SetNillableTotalOrders(v *int) *ReconciliationCreate {
	if v != nil {
		_c.SetTotalOrders(*v)
	}
	return _c
}

// SetMatchedOrders sets the "matched_orders" field.
func (_c *ReconciliationCreate) SetMatchedOrders(v int) *ReconciliationCreate {
	_c.mutation.SetMatchedOrders(v)
	return _c
}

// SetNillableMatchedOrders sets the "matched_orders" field if the given value is not nil.
func (_c *ReconciliationCreate) SetNillableMatchedOrders(v *int) *ReconciliationCreate {
	if v != nil {
		_c.SetMatchedOrders(*v)
	}
	return _c
}

// SetExceptionOrders sets the "exception_orders" field.
func (_c *ReconciliationCreate) SetExceptionOrders(v int) *ReconciliationCreate {
	_c.mutation.SetExceptionOrders(v)
	return _c
}

// SetNillableExceptionOrders sets the "exception_orders" field if the given value is not nil.
func (_c *ReconciliationCreate) SetNillableExceptionOrders(v *int) *ReconciliationCreate {
	if v != nil {
		_c.SetExceptionOrders(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReconciliationCreate) SetCreatedAt(v time.Time) *ReconciliationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReconciliationCreate) SetNillableCreatedAt(v *time.Time) *ReconciliationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReconciliationCreate) SetUpdatedAt(v time.Time) *ReconciliationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReconciliationCreate) SetNillableUpdatedAt(v *time.Time) *ReconciliationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReconciliationCreate) SetID(v uuid.UUID) *ReconciliationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ReconciliationCreate) SetNillableID(v *uuid.UUID) *ReconciliationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ReconciliationMutation object of the builder.
func (_c *ReconciliationCreate) Mutation() *ReconciliationMutation {
	return _c.mutation
}

// Save creates the Reconciliation in the database.
func (_c *ReconciliationCreate) Save(ctx context.Context) (*Reconciliation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReconciliationCreate) SaveX(ctx context.Context) *Reconciliation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReconciliationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReconciliationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReconciliationCreate) defaults() {
	if _, ok := _c.mutation.PayMethod(); !ok {
		v := reconciliation.DefaultPayMethod
		_c.mutation.SetPayMethod(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := reconciliation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalOrders(); !ok {
		v := reconciliation.DefaultTotalOrders
		_c.mutation.SetTotalOrders(v)
	}
	if _, ok := _c.mutation.MatchedOrders(); !ok {
		v := reconciliation.DefaultMatchedOrders
		_c.mutation.SetMatchedOrders(v)
	}
	if _, ok := _c.mutation.ExceptionOrders(); !ok {
		v := reconciliation.DefaultExceptionOrders
		_c.mutation.SetExceptionOrders(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := reconciliation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := reconciliation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := reconciliation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReconciliationCreate) check() error {
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Reconciliation.date"`)}
	}
	if _, ok := _c.mutation.PayMethod(); !ok {
		return &ValidationError{Name: "pay_method", err: errors.New(`ent: missing required field "Reconciliation.pay_method"`)}
	}
	if v, ok := _c.mutation.PayMethod(); ok {
		if err := reconciliation.PayMethodValidator(v); err != nil {
			return &ValidationError{Name: "pay_method", err: fmt.Errorf(`ent: validator failed for field "Reconciliation.pay_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Reconciliation.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := reconciliation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Reconciliation.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalOrders(); !ok {
		return &ValidationError{Name: "total_orders", err: errors.New(`ent: missing required field "Reconciliation.total_orders"`)}
	}
	if _, ok := _c.mutation.MatchedOrders(); !ok {
		return &ValidationError{Name: "matched_orders", err: errors.New(`ent: missing required field "Reconciliation.matched_orders"`)}
	}
	if _, ok := _c.mutation.ExceptionOrders(); !ok {
		return &ValidationError{Name: "exception_orders", err: errors.New(`ent: missing required field "Reconciliation.exception_orders"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Reconciliation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Reconciliation.updated_at"`)}
	}
	return nil
}

func (_c *ReconciliationCreate) sqlSave(ctx context.Context) (*Reconciliation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReconciliationCreate) createSpec() (*Reconciliation, *sqlgraph.CreateSpec) {
	var (
		_node = &Reconciliation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reconciliation.Table, sqlgraph.NewFieldSpec(reconciliation.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(reconciliation.FieldDate, field.TypeString, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.PayMethod(); ok {
		_spec.SetField(reconciliation.FieldPayMethod, field.TypeEnum, value)
		_node.PayMethod = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(reconciliation.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalOrders(); ok {
		_spec.SetField(reconciliation.FieldTotalOrders, field.TypeInt, value)
		_node.TotalOrders = value
	}
	if value, ok := _c.mutation.MatchedOrders(); ok {
		_spec.SetField(reconciliation.FieldMatchedOrders, field.TypeInt, value)
		_node.MatchedOrders = value
	}
	if value, ok := _c.mutation.ExceptionOrders(); ok {
		_spec.SetField(reconciliation.FieldExceptionOrders, field.TypeInt, value)
		_node.ExceptionOrders = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reconciliation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reconciliation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ReconciliationCreateBulk is the builder for creating many Reconciliation entities in bulk.
type ReconciliationCreateBulk struct {
	config
	err      error
	builders []*ReconciliationCreate
}

// Save creates the Reconciliation entities in the database.
func (_c *ReconciliationCreateBulk) Save(ctx context.Context) ([]*Reconciliation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Reconciliation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReconciliationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReconciliationCreateBulk) SaveX(ctx context.Context) []*Reconciliation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReconciliationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReconciliationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
