// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuanyiying/smart-park/internal/payment/data/ent/predicate"
	"github.com/xuanyiying/smart-park/internal/payment/data/ent/refundapproval"
)

// RefundApprovalDelete is the builder for deleting a RefundApproval entity.
type RefundApprovalDelete struct {
	config
	hooks    []Hook
	mutation *RefundApprovalMutation
}

// Where appends a list predicates to the RefundApprovalDelete builder.
func (_d *RefundApprovalDelete) Where(ps ...predicate.RefundApproval) *RefundApprovalDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RefundApprovalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RefundApprovalDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RefundApprovalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(refundapproval.Table, sqlgraph.NewFieldSpec(refundapproval.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RefundApprovalDeleteOne is the builder for deleting a single RefundApproval entity.
type RefundApprovalDeleteOne struct {
	_d *RefundApprovalDelete
}

// Where appends a list predicates to the RefundApprovalDelete builder.
func (_d *RefundApprovalDeleteOne) Where(ps ...predicate.RefundApproval) *RefundApprovalDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RefundApprovalDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{refundapproval.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RefundApprovalDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
