// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/admin/v1/admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminServiceCreateParkingLot = "/api.admin.v1.AdminService/CreateParkingLot"
const OperationAdminServiceCreateVehicle = "/api.admin.v1.AdminService/CreateVehicle"
const OperationAdminServiceGetDailyReport = "/api.admin.v1.AdminService/GetDailyReport"
const OperationAdminServiceGetMonthlyReport = "/api.admin.v1.AdminService/GetMonthlyReport"
const OperationAdminServiceGetOrder = "/api.admin.v1.AdminService/GetOrder"
const OperationAdminServiceGetParkingLot = "/api.admin.v1.AdminService/GetParkingLot"
const OperationAdminServiceListOrders = "/api.admin.v1.AdminService/ListOrders"
const OperationAdminServiceListParkingLots = "/api.admin.v1.AdminService/ListParkingLots"
const OperationAdminServiceListParkingRecords = "/api.admin.v1.AdminService/ListParkingRecords"
const OperationAdminServiceListVehicles = "/api.admin.v1.AdminService/ListVehicles"
const OperationAdminServiceUpdateParkingLot = "/api.admin.v1.AdminService/UpdateParkingLot"

type AdminServiceHTTPServer interface {
	CreateParkingLot(context.Context, *CreateParkingLotRequest) (*CreateParkingLotResponse, error)
	CreateVehicle(context.Context, *CreateVehicleRequest) (*CreateVehicleResponse, error)
	GetDailyReport(context.Context, *GetDailyReportRequest) (*GetDailyReportResponse, error)
	GetMonthlyReport(context.Context, *GetMonthlyReportRequest) (*GetMonthlyReportResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	GetParkingLot(context.Context, *GetParkingLotRequest) (*GetParkingLotResponse, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	ListParkingLots(context.Context, *ListParkingLotsRequest) (*ListParkingLotsResponse, error)
	ListParkingRecords(context.Context, *ListParkingRecordsRequest) (*ListParkingRecordsResponse, error)
	ListVehicles(context.Context, *ListVehiclesRequest) (*ListVehiclesResponse, error)
	UpdateParkingLot(context.Context, *UpdateParkingLotRequest) (*UpdateParkingLotResponse, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/admin/lots", _AdminService_CreateParkingLot0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/lots/{id}", _AdminService_GetParkingLot0_HTTP_Handler(srv))
	r.PUT("/api/v1/admin/lots/{id}", _AdminService_UpdateParkingLot0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/lots", _AdminService_ListParkingLots0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/records", _AdminService_ListParkingRecords0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/orders", _AdminService_ListOrders0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/orders/{id}", _AdminService_GetOrder0_HTTP_Handler(srv))
	r.POST("/api/v1/admin/vehicles", _AdminService_CreateVehicle0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/vehicles", _AdminService_ListVehicles0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/reports/daily", _AdminService_GetDailyReport0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/reports/monthly", _AdminService_GetMonthlyReport0_HTTP_Handler(srv))
}

func _AdminService_CreateParkingLot0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateParkingLotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateParkingLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateParkingLot(ctx, req.(*CreateParkingLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateParkingLotResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetParkingLot0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetParkingLotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetParkingLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetParkingLot(ctx, req.(*GetParkingLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetParkingLotResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateParkingLot0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateParkingLotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateParkingLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateParkingLot(ctx, req.(*UpdateParkingLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateParkingLotResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListParkingLots0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListParkingLotsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListParkingLots)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListParkingLots(ctx, req.(*ListParkingLotsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListParkingLotsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListParkingRecords0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListParkingRecordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListParkingRecords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListParkingRecords(ctx, req.(*ListParkingRecordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListParkingRecordsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListOrders0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrders(ctx, req.(*ListOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrdersResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetOrder0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrder(ctx, req.(*GetOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateVehicle0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateVehicleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateVehicle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateVehicle(ctx, req.(*CreateVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateVehicleResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListVehicles0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListVehiclesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListVehicles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVehicles(ctx, req.(*ListVehiclesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVehiclesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetDailyReport0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDailyReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetDailyReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDailyReport(ctx, req.(*GetDailyReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDailyReportResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetMonthlyReport0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMonthlyReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetMonthlyReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMonthlyReport(ctx, req.(*GetMonthlyReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMonthlyReportResponse)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	CreateParkingLot(ctx context.Context, req *CreateParkingLotRequest, opts ...http.CallOption) (rsp *CreateParkingLotResponse, err error)
	CreateVehicle(ctx context.Context, req *CreateVehicleRequest, opts ...http.CallOption) (rsp *CreateVehicleResponse, err error)
	GetDailyReport(ctx context.Context, req *GetDailyReportRequest, opts ...http.CallOption) (rsp *GetDailyReportResponse, err error)
	GetMonthlyReport(ctx context.Context, req *GetMonthlyReportRequest, opts ...http.CallOption) (rsp *GetMonthlyReportResponse, err error)
	GetOrder(ctx context.Context, req *GetOrderRequest, opts ...http.CallOption) (rsp *GetOrderResponse, err error)
	GetParkingLot(ctx context.Context, req *GetParkingLotRequest, opts ...http.CallOption) (rsp *GetParkingLotResponse, err error)
	ListOrders(ctx context.Context, req *ListOrdersRequest, opts ...http.CallOption) (rsp *ListOrdersResponse, err error)
	ListParkingLots(ctx context.Context, req *ListParkingLotsRequest, opts ...http.CallOption) (rsp *ListParkingLotsResponse, err error)
	ListParkingRecords(ctx context.Context, req *ListParkingRecordsRequest, opts ...http.CallOption) (rsp *ListParkingRecordsResponse, err error)
	ListVehicles(ctx context.Context, req *ListVehiclesRequest, opts ...http.CallOption) (rsp *ListVehiclesResponse, err error)
	UpdateParkingLot(ctx context.Context, req *UpdateParkingLotRequest, opts ...http.CallOption) (rsp *UpdateParkingLotResponse, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

func (c *AdminServiceHTTPClientImpl) CreateParkingLot(ctx context.Context, in *CreateParkingLotRequest, opts ...http.CallOption) (*CreateParkingLotResponse, error) {
	var out CreateParkingLotResponse
	pattern := "/api/v1/admin/lots"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceCreateParkingLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateVehicle(ctx context.Context, in *CreateVehicleRequest, opts ...http.CallOption) (*CreateVehicleResponse, error) {
	var out CreateVehicleResponse
	pattern := "/api/v1/admin/vehicles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceCreateVehicle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetDailyReport(ctx context.Context, in *GetDailyReportRequest, opts ...http.CallOption) (*GetDailyReportResponse, error) {
	var out GetDailyReportResponse
	pattern := "/api/v1/admin/reports/daily"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetDailyReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetMonthlyReport(ctx context.Context, in *GetMonthlyReportRequest, opts ...http.CallOption) (*GetMonthlyReportResponse, error) {
	var out GetMonthlyReportResponse
	pattern := "/api/v1/admin/reports/monthly"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetMonthlyReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...http.CallOption) (*GetOrderResponse, error) {
	var out GetOrderResponse
	pattern := "/api/v1/admin/orders/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetParkingLot(ctx context.Context, in *GetParkingLotRequest, opts ...http.CallOption) (*GetParkingLotResponse, error) {
	var out GetParkingLotResponse
	pattern := "/api/v1/admin/lots/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetParkingLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...http.CallOption) (*ListOrdersResponse, error) {
	var out ListOrdersResponse
	pattern := "/api/v1/admin/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListParkingLots(ctx context.Context, in *ListParkingLotsRequest, opts ...http.CallOption) (*ListParkingLotsResponse, error) {
	var out ListParkingLotsResponse
	pattern := "/api/v1/admin/lots"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListParkingLots))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListParkingRecords(ctx context.Context, in *ListParkingRecordsRequest, opts ...http.CallOption) (*ListParkingRecordsResponse, error) {
	var out ListParkingRecordsResponse
	pattern := "/api/v1/admin/records"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListParkingRecords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...http.CallOption) (*ListVehiclesResponse, error) {
	var out ListVehiclesResponse
	pattern := "/api/v1/admin/vehicles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListVehicles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateParkingLot(ctx context.Context, in *UpdateParkingLotRequest, opts ...http.CallOption) (*UpdateParkingLotResponse, error) {
	var out UpdateParkingLotResponse
	pattern := "/api/v1/admin/lots/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceUpdateParkingLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
