// Code generated by ent, DO NOT EDIT.

package deviceperformance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldID, id))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldDeviceID, v))
}

// CPUUsage applies equality check predicate on the "cpu_usage" field. It's identical to CPUUsageEQ.
func CPUUsage(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldCPUUsage, v))
}

// MemoryUsage applies equality check predicate on the "memory_usage" field. It's identical to MemoryUsageEQ.
func MemoryUsage(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldMemoryUsage, v))
}

// StorageUsage applies equality check predicate on the "storage_usage" field. It's identical to StorageUsageEQ.
func StorageUsage(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldStorageUsage, v))
}

// NetworkIn applies equality check predicate on the "network_in" field. It's identical to NetworkInEQ.
func NetworkIn(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldNetworkIn, v))
}

// NetworkOut applies equality check predicate on the "network_out" field. It's identical to NetworkOutEQ.
func NetworkOut(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldNetworkOut, v))
}

// Temperature applies equality check predicate on the "temperature" field. It's identical to TemperatureEQ.
func Temperature(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldTemperature, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldTimestamp, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldCreatedAt, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldContainsFold(FieldDeviceID, v))
}

// CPUUsageEQ applies the EQ predicate on the "cpu_usage" field.
func CPUUsageEQ(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldCPUUsage, v))
}

// CPUUsageNEQ applies the NEQ predicate on the "cpu_usage" field.
func CPUUsageNEQ(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldCPUUsage, v))
}

// CPUUsageIn applies the In predicate on the "cpu_usage" field.
func CPUUsageIn(vs ...float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldCPUUsage, vs...))
}

// CPUUsageNotIn applies the NotIn predicate on the "cpu_usage" field.
func CPUUsageNotIn(vs ...float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldCPUUsage, vs...))
}

// CPUUsageGT applies the GT predicate on the "cpu_usage" field.
func CPUUsageGT(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldCPUUsage, v))
}

// CPUUsageGTE applies the GTE predicate on the "cpu_usage" field.
func CPUUsageGTE(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldCPUUsage, v))
}

// CPUUsageLT applies the LT predicate on the "cpu_usage" field.
func CPUUsageLT(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldCPUUsage, v))
}

// CPUUsageLTE applies the LTE predicate on the "cpu_usage" field.
func CPUUsageLTE(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldCPUUsage, v))
}

// MemoryUsageEQ applies the EQ predicate on the "memory_usage" field.
func MemoryUsageEQ(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldMemoryUsage, v))
}

// MemoryUsageNEQ applies the NEQ predicate on the "memory_usage" field.
func MemoryUsageNEQ(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldMemoryUsage, v))
}

// MemoryUsageIn applies the In predicate on the "memory_usage" field.
func MemoryUsageIn(vs ...float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldMemoryUsage, vs...))
}

// MemoryUsageNotIn applies the NotIn predicate on the "memory_usage" field.
func MemoryUsageNotIn(vs ...float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldMemoryUsage, vs...))
}

// MemoryUsageGT applies the GT predicate on the "memory_usage" field.
func MemoryUsageGT(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldMemoryUsage, v))
}

// MemoryUsageGTE applies the GTE predicate on the "memory_usage" field.
func MemoryUsageGTE(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldMemoryUsage, v))
}

// MemoryUsageLT applies the LT predicate on the "memory_usage" field.
func MemoryUsageLT(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldMemoryUsage, v))
}

// MemoryUsageLTE applies the LTE predicate on the "memory_usage" field.
func MemoryUsageLTE(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldMemoryUsage, v))
}

// StorageUsageEQ applies the EQ predicate on the "storage_usage" field.
func StorageUsageEQ(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldStorageUsage, v))
}

// StorageUsageNEQ applies the NEQ predicate on the "storage_usage" field.
func StorageUsageNEQ(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldStorageUsage, v))
}

// StorageUsageIn applies the In predicate on the "storage_usage" field.
func StorageUsageIn(vs ...float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldStorageUsage, vs...))
}

// StorageUsageNotIn applies the NotIn predicate on the "storage_usage" field.
func StorageUsageNotIn(vs ...float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldStorageUsage, vs...))
}

// StorageUsageGT applies the GT predicate on the "storage_usage" field.
func StorageUsageGT(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldStorageUsage, v))
}

// StorageUsageGTE applies the GTE predicate on the "storage_usage" field.
func StorageUsageGTE(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldStorageUsage, v))
}

// StorageUsageLT applies the LT predicate on the "storage_usage" field.
func StorageUsageLT(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldStorageUsage, v))
}

// StorageUsageLTE applies the LTE predicate on the "storage_usage" field.
func StorageUsageLTE(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldStorageUsage, v))
}

// NetworkInEQ applies the EQ predicate on the "network_in" field.
func NetworkInEQ(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldNetworkIn, v))
}

// NetworkInNEQ applies the NEQ predicate on the "network_in" field.
func NetworkInNEQ(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldNetworkIn, v))
}

// NetworkInIn applies the In predicate on the "network_in" field.
func NetworkInIn(vs ...int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldNetworkIn, vs...))
}

// NetworkInNotIn applies the NotIn predicate on the "network_in" field.
func NetworkInNotIn(vs ...int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldNetworkIn, vs...))
}

// NetworkInGT applies the GT predicate on the "network_in" field.
func NetworkInGT(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldNetworkIn, v))
}

// NetworkInGTE applies the GTE predicate on the "network_in" field.
func NetworkInGTE(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldNetworkIn, v))
}

// NetworkInLT applies the LT predicate on the "network_in" field.
func NetworkInLT(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldNetworkIn, v))
}

// NetworkInLTE applies the LTE predicate on the "network_in" field.
func NetworkInLTE(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldNetworkIn, v))
}

// NetworkOutEQ applies the EQ predicate on the "network_out" field.
func NetworkOutEQ(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldNetworkOut, v))
}

// NetworkOutNEQ applies the NEQ predicate on the "network_out" field.
func NetworkOutNEQ(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldNetworkOut, v))
}

// NetworkOutIn applies the In predicate on the "network_out" field.
func NetworkOutIn(vs ...int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldNetworkOut, vs...))
}

// NetworkOutNotIn applies the NotIn predicate on the "network_out" field.
func NetworkOutNotIn(vs ...int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldNetworkOut, vs...))
}

// NetworkOutGT applies the GT predicate on the "network_out" field.
func NetworkOutGT(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldNetworkOut, v))
}

// NetworkOutGTE applies the GTE predicate on the "network_out" field.
func NetworkOutGTE(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldNetworkOut, v))
}

// NetworkOutLT applies the LT predicate on the "network_out" field.
func NetworkOutLT(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldNetworkOut, v))
}

// NetworkOutLTE applies the LTE predicate on the "network_out" field.
func NetworkOutLTE(v int64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldNetworkOut, v))
}

// TemperatureEQ applies the EQ predicate on the "temperature" field.
func TemperatureEQ(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldTemperature, v))
}

// TemperatureNEQ applies the NEQ predicate on the "temperature" field.
func TemperatureNEQ(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldTemperature, v))
}

// TemperatureIn applies the In predicate on the "temperature" field.
func TemperatureIn(vs ...float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldTemperature, vs...))
}

// TemperatureNotIn applies the NotIn predicate on the "temperature" field.
func TemperatureNotIn(vs ...float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldTemperature, vs...))
}

// TemperatureGT applies the GT predicate on the "temperature" field.
func TemperatureGT(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldTemperature, v))
}

// TemperatureGTE applies the GTE predicate on the "temperature" field.
func TemperatureGTE(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldTemperature, v))
}

// TemperatureLT applies the LT predicate on the "temperature" field.
func TemperatureLT(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldTemperature, v))
}

// TemperatureLTE applies the LTE predicate on the "temperature" field.
func TemperatureLTE(v float64) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldTemperature, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldTimestamp, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DevicePerformance) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DevicePerformance) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DevicePerformance) predicate.DevicePerformance {
	return predicate.DevicePerformance(sql.NotPredicates(p))
}
