// Code generated by ent, DO NOT EDIT.

package price

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the price type in the database.
	Label = "price"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStationID holds the string denoting the station_id field in the database.
	FieldStationID = "station_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStartHour holds the string denoting the start_hour field in the database.
	FieldStartHour = "start_hour"
	// FieldEndHour holds the string denoting the end_hour field in the database.
	FieldEndHour = "end_hour"
	// FieldPricePerKwh holds the string denoting the price_per_kwh field in the database.
	FieldPricePerKwh = "price_per_kwh"
	// FieldServiceFee holds the string denoting the service_fee field in the database.
	FieldServiceFee = "service_fee"
	// FieldPeakLoad holds the string denoting the peak_load field in the database.
	FieldPeakLoad = "peak_load"
	// FieldOffPeakLoad holds the string denoting the off_peak_load field in the database.
	FieldOffPeakLoad = "off_peak_load"
	// FieldIsPeakHours holds the string denoting the is_peak_hours field in the database.
	FieldIsPeakHours = "is_peak_hours"
	// FieldEffectiveAt holds the string denoting the effective_at field in the database.
	FieldEffectiveAt = "effective_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeStation holds the string denoting the station edge name in mutations.
	EdgeStation = "station"
	// Table holds the table name of the price in the database.
	Table = "prices"
	// StationTable is the table that holds the station relation/edge.
	StationTable = "prices"
	// StationInverseTable is the table name for the Station entity.
	// It exists in this package in order to avoid circular dependency with the "station" package.
	StationInverseTable = "stations"
	// StationColumn is the table column denoting the station relation/edge.
	StationColumn = "station_id"
)

// Columns holds all SQL columns for price fields.
var Columns = []string{
	FieldID,
	FieldStationID,
	FieldName,
	FieldStartHour,
	FieldEndHour,
	FieldPricePerKwh,
	FieldServiceFee,
	FieldPeakLoad,
	FieldOffPeakLoad,
	FieldIsPeakHours,
	FieldEffectiveAt,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// StartHourValidator is a validator for the "start_hour" field. It is called by the builders before save.
	StartHourValidator func(int) error
	// EndHourValidator is a validator for the "end_hour" field. It is called by the builders before save.
	EndHourValidator func(int) error
	// DefaultPricePerKwh holds the default value on creation for the "price_per_kwh" field.
	DefaultPricePerKwh float64
	// DefaultServiceFee holds the default value on creation for the "service_fee" field.
	DefaultServiceFee float64
	// DefaultPeakLoad holds the default value on creation for the "peak_load" field.
	DefaultPeakLoad float64
	// DefaultOffPeakLoad holds the default value on creation for the "off_peak_load" field.
	DefaultOffPeakLoad float64
	// DefaultIsPeakHours holds the default value on creation for the "is_peak_hours" field.
	DefaultIsPeakHours bool
	// DefaultEffectiveAt holds the default value on creation for the "effective_at" field.
	DefaultEffectiveAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Price queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStationID orders the results by the station_id field.
func ByStationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStationID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStartHour orders the results by the start_hour field.
func ByStartHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartHour, opts...).ToFunc()
}

// ByEndHour orders the results by the end_hour field.
func ByEndHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndHour, opts...).ToFunc()
}

// ByPricePerKwh orders the results by the price_per_kwh field.
func ByPricePerKwh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricePerKwh, opts...).ToFunc()
}

// ByServiceFee orders the results by the service_fee field.
func ByServiceFee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceFee, opts...).ToFunc()
}

// ByPeakLoad orders the results by the peak_load field.
func ByPeakLoad(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakLoad, opts...).ToFunc()
}

// ByOffPeakLoad orders the results by the off_peak_load field.
func ByOffPeakLoad(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOffPeakLoad, opts...).ToFunc()
}

// ByIsPeakHours orders the results by the is_peak_hours field.
func ByIsPeakHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPeakHours, opts...).ToFunc()
}

// ByEffectiveAt orders the results by the effective_at field.
func ByEffectiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStationField orders the results by station field.
func ByStationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStationStep(), sql.OrderByField(field, opts...))
	}
}
func newStationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StationTable, StationColumn),
	)
}
