// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/xuanyiying/smart-park/internal/multitenancy/data/ent/predicate"
	"github.com/xuanyiying/smart-park/internal/multitenancy/data/ent/tenant"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantUpdate) SetCode(v string) *TenantUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCode(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v tenant.Status) *TenantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStatus(v *tenant.Status) *TenantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMaxParkingLots sets the "max_parking_lots" field.
func (_u *TenantUpdate) SetMaxParkingLots(v int) *TenantUpdate {
	_u.mutation.ResetMaxParkingLots()
	_u.mutation.SetMaxParkingLots(v)
	return _u
}

// SetNillableMaxParkingLots sets the "max_parking_lots" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableMaxParkingLots(v *int) *TenantUpdate {
	if v != nil {
		_u.SetMaxParkingLots(*v)
	}
	return _u
}

// AddMaxParkingLots adds value to the "max_parking_lots" field.
func (_u *TenantUpdate) AddMaxParkingLots(v int) *TenantUpdate {
	_u.mutation.AddMaxParkingLots(v)
	return _u
}

// SetMaxDevices sets the "max_devices" field.
func (_u *TenantUpdate) SetMaxDevices(v int) *TenantUpdate {
	_u.mutation.ResetMaxDevices()
	_u.mutation.SetMaxDevices(v)
	return _u
}

// SetNillableMaxDevices sets the "max_devices" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableMaxDevices(v *int) *TenantUpdate {
	if v != nil {
		_u.SetMaxDevices(*v)
	}
	return _u
}

// AddMaxDevices adds value to the "max_devices" field.
func (_u *TenantUpdate) AddMaxDevices(v int) *TenantUpdate {
	_u.mutation.AddMaxDevices(v)
	return _u
}

// SetMaxUsers sets the "max_users" field.
func (_u *TenantUpdate) SetMaxUsers(v int) *TenantUpdate {
	_u.mutation.ResetMaxUsers()
	_u.mutation.SetMaxUsers(v)
	return _u
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableMaxUsers(v *int) *TenantUpdate {
	if v != nil {
		_u.SetMaxUsers(*v)
	}
	return _u
}

// AddMaxUsers adds value to the "max_users" field.
func (_u *TenantUpdate) AddMaxUsers(v int) *TenantUpdate {
	_u.mutation.AddMaxUsers(v)
	return _u
}

// SetStorageQuota sets the "storage_quota" field.
func (_u *TenantUpdate) SetStorageQuota(v int64) *TenantUpdate {
	_u.mutation.ResetStorageQuota()
	_u.mutation.SetStorageQuota(v)
	return _u
}

// SetNillableStorageQuota sets the "storage_quota" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStorageQuota(v *int64) *TenantUpdate {
	if v != nil {
		_u.SetStorageQuota(*v)
	}
	return _u
}

// AddStorageQuota adds value to the "storage_quota" field.
func (_u *TenantUpdate) AddStorageQuota(v int64) *TenantUpdate {
	_u.mutation.AddStorageQuota(v)
	return _u
}

// SetFeatures sets the "features" field.
func (_u *TenantUpdate) SetFeatures(v []string) *TenantUpdate {
	_u.mutation.SetFeatures(v)
	return _u
}

// AppendFeatures appends value to the "features" field.
func (_u *TenantUpdate) AppendFeatures(v []string) *TenantUpdate {
	_u.mutation.AppendFeatures(v)
	return _u
}

// SetCustomDomain sets the "custom_domain" field.
func (_u *TenantUpdate) SetCustomDomain(v string) *TenantUpdate {
	_u.mutation.SetCustomDomain(v)
	return _u
}

// SetNillableCustomDomain sets the "custom_domain" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCustomDomain(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCustomDomain(*v)
	}
	return _u
}

// ClearCustomDomain clears the value of the "custom_domain" field.
func (_u *TenantUpdate) ClearCustomDomain() *TenantUpdate {
	_u.mutation.ClearCustomDomain()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TenantUpdate) SetTimezone(v string) *TenantUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableTimezone(v *string) *TenantUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *TenantUpdate) SetCurrency(v string) *TenantUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCurrency(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *TenantUpdate) SetLanguage(v string) *TenantUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableLanguage(v *string) *TenantUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *TenantUpdate) SetExpiredAt(v time.Time) *TenantUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableExpiredAt(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *TenantUpdate) ClearExpiredAt() *TenantUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := tenant.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Tenant.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Tenant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CustomDomain(); ok {
		if err := tenant.CustomDomainValidator(v); err != nil {
			return &ValidationError{Name: "custom_domain", err: fmt.Errorf(`ent: validator failed for field "Tenant.custom_domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := tenant.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Tenant.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := tenant.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Tenant.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := tenant.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Tenant.language": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MaxParkingLots(); ok {
		_spec.SetField(tenant.FieldMaxParkingLots, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxParkingLots(); ok {
		_spec.AddField(tenant.FieldMaxParkingLots, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxDevices(); ok {
		_spec.SetField(tenant.FieldMaxDevices, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDevices(); ok {
		_spec.AddField(tenant.FieldMaxDevices, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxUsers(); ok {
		_spec.SetField(tenant.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUsers(); ok {
		_spec.AddField(tenant.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StorageQuota(); ok {
		_spec.SetField(tenant.FieldStorageQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStorageQuota(); ok {
		_spec.AddField(tenant.FieldStorageQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(tenant.FieldFeatures, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFeatures(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldFeatures, value)
		})
	}
	if value, ok := _u.mutation.CustomDomain(); ok {
		_spec.SetField(tenant.FieldCustomDomain, field.TypeString, value)
	}
	if _u.mutation.CustomDomainCleared() {
		_spec.ClearField(tenant.FieldCustomDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(tenant.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(tenant.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(tenant.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(tenant.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(tenant.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantUpdateOne) SetCode(v string) *TenantUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCode(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v tenant.Status) *TenantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStatus(v *tenant.Status) *TenantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMaxParkingLots sets the "max_parking_lots" field.
func (_u *TenantUpdateOne) SetMaxParkingLots(v int) *TenantUpdateOne {
	_u.mutation.ResetMaxParkingLots()
	_u.mutation.SetMaxParkingLots(v)
	return _u
}

// SetNillableMaxParkingLots sets the "max_parking_lots" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableMaxParkingLots(v *int) *TenantUpdateOne {
	if v != nil {
		_u.SetMaxParkingLots(*v)
	}
	return _u
}

// AddMaxParkingLots adds value to the "max_parking_lots" field.
func (_u *TenantUpdateOne) AddMaxParkingLots(v int) *TenantUpdateOne {
	_u.mutation.AddMaxParkingLots(v)
	return _u
}

// SetMaxDevices sets the "max_devices" field.
func (_u *TenantUpdateOne) SetMaxDevices(v int) *TenantUpdateOne {
	_u.mutation.ResetMaxDevices()
	_u.mutation.SetMaxDevices(v)
	return _u
}

// SetNillableMaxDevices sets the "max_devices" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableMaxDevices(v *int) *TenantUpdateOne {
	if v != nil {
		_u.SetMaxDevices(*v)
	}
	return _u
}

// AddMaxDevices adds value to the "max_devices" field.
func (_u *TenantUpdateOne) AddMaxDevices(v int) *TenantUpdateOne {
	_u.mutation.AddMaxDevices(v)
	return _u
}

// SetMaxUsers sets the "max_users" field.
func (_u *TenantUpdateOne) SetMaxUsers(v int) *TenantUpdateOne {
	_u.mutation.ResetMaxUsers()
	_u.mutation.SetMaxUsers(v)
	return _u
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableMaxUsers(v *int) *TenantUpdateOne {
	if v != nil {
		_u.SetMaxUsers(*v)
	}
	return _u
}

// AddMaxUsers adds value to the "max_users" field.
func (_u *TenantUpdateOne) AddMaxUsers(v int) *TenantUpdateOne {
	_u.mutation.AddMaxUsers(v)
	return _u
}

// SetStorageQuota sets the "storage_quota" field.
func (_u *TenantUpdateOne) SetStorageQuota(v int64) *TenantUpdateOne {
	_u.mutation.ResetStorageQuota()
	_u.mutation.SetStorageQuota(v)
	return _u
}

// SetNillableStorageQuota sets the "storage_quota" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStorageQuota(v *int64) *TenantUpdateOne {
	if v != nil {
		_u.SetStorageQuota(*v)
	}
	return _u
}

// AddStorageQuota adds value to the "storage_quota" field.
func (_u *TenantUpdateOne) AddStorageQuota(v int64) *TenantUpdateOne {
	_u.mutation.AddStorageQuota(v)
	return _u
}

// SetFeatures sets the "features" field.
func (_u *TenantUpdateOne) SetFeatures(v []string) *TenantUpdateOne {
	_u.mutation.SetFeatures(v)
	return _u
}

// AppendFeatures appends value to the "features" field.
func (_u *TenantUpdateOne) AppendFeatures(v []string) *TenantUpdateOne {
	_u.mutation.AppendFeatures(v)
	return _u
}

// SetCustomDomain sets the "custom_domain" field.
func (_u *TenantUpdateOne) SetCustomDomain(v string) *TenantUpdateOne {
	_u.mutation.SetCustomDomain(v)
	return _u
}

// SetNillableCustomDomain sets the "custom_domain" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCustomDomain(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCustomDomain(*v)
	}
	return _u
}

// ClearCustomDomain clears the value of the "custom_domain" field.
func (_u *TenantUpdateOne) ClearCustomDomain() *TenantUpdateOne {
	_u.mutation.ClearCustomDomain()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TenantUpdateOne) SetTimezone(v string) *TenantUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableTimezone(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *TenantUpdateOne) SetCurrency(v string) *TenantUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCurrency(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *TenantUpdateOne) SetLanguage(v string) *TenantUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableLanguage(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *TenantUpdateOne) SetExpiredAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableExpiredAt(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *TenantUpdateOne) ClearExpiredAt() *TenantUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := tenant.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Tenant.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Tenant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CustomDomain(); ok {
		if err := tenant.CustomDomainValidator(v); err != nil {
			return &ValidationError{Name: "custom_domain", err: fmt.Errorf(`ent: validator failed for field "Tenant.custom_domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := tenant.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Tenant.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := tenant.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Tenant.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := tenant.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Tenant.language": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MaxParkingLots(); ok {
		_spec.SetField(tenant.FieldMaxParkingLots, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxParkingLots(); ok {
		_spec.AddField(tenant.FieldMaxParkingLots, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxDevices(); ok {
		_spec.SetField(tenant.FieldMaxDevices, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDevices(); ok {
		_spec.AddField(tenant.FieldMaxDevices, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxUsers(); ok {
		_spec.SetField(tenant.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUsers(); ok {
		_spec.AddField(tenant.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StorageQuota(); ok {
		_spec.SetField(tenant.FieldStorageQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStorageQuota(); ok {
		_spec.AddField(tenant.FieldStorageQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(tenant.FieldFeatures, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFeatures(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldFeatures, value)
		})
	}
	if value, ok := _u.mutation.CustomDomain(); ok {
		_spec.SetField(tenant.FieldCustomDomain, field.TypeString, value)
	}
	if _u.mutation.CustomDomainCleared() {
		_spec.ClearField(tenant.FieldCustomDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(tenant.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(tenant.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(tenant.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(tenant.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(tenant.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
