// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/admin/data/ent/parkingrecord"
)

// ParkingRecordCreate is the builder for creating a ParkingRecord entity.
type ParkingRecordCreate struct {
	config
	mutation *ParkingRecordMutation
	hooks    []Hook
}

// SetLotID sets the "lot_id" field.
func (_c *ParkingRecordCreate) SetLotID(v uuid.UUID) *ParkingRecordCreate {
	_c.mutation.SetLotID(v)
	return _c
}

// SetEntryLaneID sets the "entry_lane_id" field.
func (_c *ParkingRecordCreate) SetEntryLaneID(v uuid.UUID) *ParkingRecordCreate {
	_c.mutation.SetEntryLaneID(v)
	return _c
}

// SetVehicleID sets the "vehicle_id" field.
func (_c *ParkingRecordCreate) SetVehicleID(v uuid.UUID) *ParkingRecordCreate {
	_c.mutation.SetVehicleID(v)
	return _c
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableVehicleID(v *uuid.UUID) *ParkingRecordCreate {
	if v != nil {
		_c.SetVehicleID(*v)
	}
	return _c
}

// SetPlateNumber sets the "plate_number" field.
func (_c *ParkingRecordCreate) SetPlateNumber(v string) *ParkingRecordCreate {
	_c.mutation.SetPlateNumber(v)
	return _c
}

// SetNillablePlateNumber sets the "plate_number" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillablePlateNumber(v *string) *ParkingRecordCreate {
	if v != nil {
		_c.SetPlateNumber(*v)
	}
	return _c
}

// SetPlateNumberSource sets the "plate_number_source" field.
func (_c *ParkingRecordCreate) SetPlateNumberSource(v parkingrecord.PlateNumberSource) *ParkingRecordCreate {
	_c.mutation.SetPlateNumberSource(v)
	return _c
}

// SetNillablePlateNumberSource sets the "plate_number_source" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillablePlateNumberSource(v *parkingrecord.PlateNumberSource) *ParkingRecordCreate {
	if v != nil {
		_c.SetPlateNumberSource(*v)
	}
	return _c
}

// SetEntryTime sets the "entry_time" field.
func (_c *ParkingRecordCreate) SetEntryTime(v time.Time) *ParkingRecordCreate {
	_c.mutation.SetEntryTime(v)
	return _c
}

// SetEntryImageURL sets the "entry_image_url" field.
func (_c *ParkingRecordCreate) SetEntryImageURL(v string) *ParkingRecordCreate {
	_c.mutation.SetEntryImageURL(v)
	return _c
}

// SetNillableEntryImageURL sets the "entry_image_url" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableEntryImageURL(v *string) *ParkingRecordCreate {
	if v != nil {
		_c.SetEntryImageURL(*v)
	}
	return _c
}

// SetRecordStatus sets the "record_status" field.
func (_c *ParkingRecordCreate) SetRecordStatus(v parkingrecord.RecordStatus) *ParkingRecordCreate {
	_c.mutation.SetRecordStatus(v)
	return _c
}

// SetNillableRecordStatus sets the "record_status" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableRecordStatus(v *parkingrecord.RecordStatus) *ParkingRecordCreate {
	if v != nil {
		_c.SetRecordStatus(*v)
	}
	return _c
}

// SetExitTime sets the "exit_time" field.
func (_c *ParkingRecordCreate) SetExitTime(v time.Time) *ParkingRecordCreate {
	_c.mutation.SetExitTime(v)
	return _c
}

// SetNillableExitTime sets the "exit_time" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableExitTime(v *time.Time) *ParkingRecordCreate {
	if v != nil {
		_c.SetExitTime(*v)
	}
	return _c
}

// SetExitImageURL sets the "exit_image_url" field.
func (_c *ParkingRecordCreate) SetExitImageURL(v string) *ParkingRecordCreate {
	_c.mutation.SetExitImageURL(v)
	return _c
}

// SetNillableExitImageURL sets the "exit_image_url" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableExitImageURL(v *string) *ParkingRecordCreate {
	if v != nil {
		_c.SetExitImageURL(*v)
	}
	return _c
}

// SetExitLaneID sets the "exit_lane_id" field.
func (_c *ParkingRecordCreate) SetExitLaneID(v uuid.UUID) *ParkingRecordCreate {
	_c.mutation.SetExitLaneID(v)
	return _c
}

// SetNillableExitLaneID sets the "exit_lane_id" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableExitLaneID(v *uuid.UUID) *ParkingRecordCreate {
	if v != nil {
		_c.SetExitLaneID(*v)
	}
	return _c
}

// SetExitDeviceID sets the "exit_device_id" field.
func (_c *ParkingRecordCreate) SetExitDeviceID(v string) *ParkingRecordCreate {
	_c.mutation.SetExitDeviceID(v)
	return _c
}

// SetNillableExitDeviceID sets the "exit_device_id" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableExitDeviceID(v *string) *ParkingRecordCreate {
	if v != nil {
		_c.SetExitDeviceID(*v)
	}
	return _c
}

// SetParkingDuration sets the "parking_duration" field.
func (_c *ParkingRecordCreate) SetParkingDuration(v int) *ParkingRecordCreate {
	_c.mutation.SetParkingDuration(v)
	return _c
}

// SetNillableParkingDuration sets the "parking_duration" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableParkingDuration(v *int) *ParkingRecordCreate {
	if v != nil {
		_c.SetParkingDuration(*v)
	}
	return _c
}

// SetExitStatus sets the "exit_status" field.
func (_c *ParkingRecordCreate) SetExitStatus(v parkingrecord.ExitStatus) *ParkingRecordCreate {
	_c.mutation.SetExitStatus(v)
	return _c
}

// SetNillableExitStatus sets the "exit_status" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableExitStatus(v *parkingrecord.ExitStatus) *ParkingRecordCreate {
	if v != nil {
		_c.SetExitStatus(*v)
	}
	return _c
}

// SetPaymentLock sets the "payment_lock" field.
func (_c *ParkingRecordCreate) SetPaymentLock(v int) *ParkingRecordCreate {
	_c.mutation.SetPaymentLock(v)
	return _c
}

// SetNillablePaymentLock sets the "payment_lock" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillablePaymentLock(v *int) *ParkingRecordCreate {
	if v != nil {
		_c.SetPaymentLock(*v)
	}
	return _c
}

// SetRecordMetadata sets the "record_metadata" field.
func (_c *ParkingRecordCreate) SetRecordMetadata(v map[string]interface{}) *ParkingRecordCreate {
	_c.mutation.SetRecordMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ParkingRecordCreate) SetCreatedAt(v time.Time) *ParkingRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableCreatedAt(v *time.Time) *ParkingRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ParkingRecordCreate) SetUpdatedAt(v time.Time) *ParkingRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableUpdatedAt(v *time.Time) *ParkingRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ParkingRecordCreate) SetID(v uuid.UUID) *ParkingRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ParkingRecordCreate) SetNillableID(v *uuid.UUID) *ParkingRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ParkingRecordMutation object of the builder.
func (_c *ParkingRecordCreate) Mutation() *ParkingRecordMutation {
	return _c.mutation
}

// Save creates the ParkingRecord in the database.
func (_c *ParkingRecordCreate) Save(ctx context.Context) (*ParkingRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ParkingRecordCreate) SaveX(ctx context.Context) *ParkingRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParkingRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParkingRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ParkingRecordCreate) defaults() {
	if _, ok := _c.mutation.RecordStatus(); !ok {
		v := parkingrecord.DefaultRecordStatus
		_c.mutation.SetRecordStatus(v)
	}
	if _, ok := _c.mutation.ParkingDuration(); !ok {
		v := parkingrecord.DefaultParkingDuration
		_c.mutation.SetParkingDuration(v)
	}
	if _, ok := _c.mutation.ExitStatus(); !ok {
		v := parkingrecord.DefaultExitStatus
		_c.mutation.SetExitStatus(v)
	}
	if _, ok := _c.mutation.PaymentLock(); !ok {
		v := parkingrecord.DefaultPaymentLock
		_c.mutation.SetPaymentLock(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := parkingrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := parkingrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := parkingrecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ParkingRecordCreate) check() error {
	if _, ok := _c.mutation.LotID(); !ok {
		return &ValidationError{Name: "lot_id", err: errors.New(`ent: missing required field "ParkingRecord.lot_id"`)}
	}
	if _, ok := _c.mutation.EntryLaneID(); !ok {
		return &ValidationError{Name: "entry_lane_id", err: errors.New(`ent: missing required field "ParkingRecord.entry_lane_id"`)}
	}
	if v, ok := _c.mutation.PlateNumber(); ok {
		if err := parkingrecord.PlateNumberValidator(v); err != nil {
			return &ValidationError{Name: "plate_number", err: fmt.Errorf(`ent: validator failed for field "ParkingRecord.plate_number": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PlateNumberSource(); ok {
		if err := parkingrecord.PlateNumberSourceValidator(v); err != nil {
			return &ValidationError{Name: "plate_number_source", err: fmt.Errorf(`ent: validator failed for field "ParkingRecord.plate_number_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntryTime(); !ok {
		return &ValidationError{Name: "entry_time", err: errors.New(`ent: missing required field "ParkingRecord.entry_time"`)}
	}
	if v, ok := _c.mutation.EntryImageURL(); ok {
		if err := parkingrecord.EntryImageURLValidator(v); err != nil {
			return &ValidationError{Name: "entry_image_url", err: fmt.Errorf(`ent: validator failed for field "ParkingRecord.entry_image_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecordStatus(); !ok {
		return &ValidationError{Name: "record_status", err: errors.New(`ent: missing required field "ParkingRecord.record_status"`)}
	}
	if v, ok := _c.mutation.RecordStatus(); ok {
		if err := parkingrecord.RecordStatusValidator(v); err != nil {
			return &ValidationError{Name: "record_status", err: fmt.Errorf(`ent: validator failed for field "ParkingRecord.record_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitImageURL(); ok {
		if err := parkingrecord.ExitImageURLValidator(v); err != nil {
			return &ValidationError{Name: "exit_image_url", err: fmt.Errorf(`ent: validator failed for field "ParkingRecord.exit_image_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitDeviceID(); ok {
		if err := parkingrecord.ExitDeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "exit_device_id", err: fmt.Errorf(`ent: validator failed for field "ParkingRecord.exit_device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExitStatus(); !ok {
		return &ValidationError{Name: "exit_status", err: errors.New(`ent: missing required field "ParkingRecord.exit_status"`)}
	}
	if v, ok := _c.mutation.ExitStatus(); ok {
		if err := parkingrecord.ExitStatusValidator(v); err != nil {
			return &ValidationError{Name: "exit_status", err: fmt.Errorf(`ent: validator failed for field "ParkingRecord.exit_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentLock(); !ok {
		return &ValidationError{Name: "payment_lock", err: errors.New(`ent: missing required field "ParkingRecord.payment_lock"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ParkingRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ParkingRecord.updated_at"`)}
	}
	return nil
}

func (_c *ParkingRecordCreate) sqlSave(ctx context.Context) (*ParkingRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ParkingRecordCreate) createSpec() (*ParkingRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &ParkingRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(parkingrecord.Table, sqlgraph.NewFieldSpec(parkingrecord.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.LotID(); ok {
		_spec.SetField(parkingrecord.FieldLotID, field.TypeUUID, value)
		_node.LotID = value
	}
	if value, ok := _c.mutation.EntryLaneID(); ok {
		_spec.SetField(parkingrecord.FieldEntryLaneID, field.TypeUUID, value)
		_node.EntryLaneID = value
	}
	if value, ok := _c.mutation.VehicleID(); ok {
		_spec.SetField(parkingrecord.FieldVehicleID, field.TypeUUID, value)
		_node.VehicleID = &value
	}
	if value, ok := _c.mutation.PlateNumber(); ok {
		_spec.SetField(parkingrecord.FieldPlateNumber, field.TypeString, value)
		_node.PlateNumber = &value
	}
	if value, ok := _c.mutation.PlateNumberSource(); ok {
		_spec.SetField(parkingrecord.FieldPlateNumberSource, field.TypeEnum, value)
		_node.PlateNumberSource = value
	}
	if value, ok := _c.mutation.EntryTime(); ok {
		_spec.SetField(parkingrecord.FieldEntryTime, field.TypeTime, value)
		_node.EntryTime = value
	}
	if value, ok := _c.mutation.EntryImageURL(); ok {
		_spec.SetField(parkingrecord.FieldEntryImageURL, field.TypeString, value)
		_node.EntryImageURL = value
	}
	if value, ok := _c.mutation.RecordStatus(); ok {
		_spec.SetField(parkingrecord.FieldRecordStatus, field.TypeEnum, value)
		_node.RecordStatus = value
	}
	if value, ok := _c.mutation.ExitTime(); ok {
		_spec.SetField(parkingrecord.FieldExitTime, field.TypeTime, value)
		_node.ExitTime = &value
	}
	if value, ok := _c.mutation.ExitImageURL(); ok {
		_spec.SetField(parkingrecord.FieldExitImageURL, field.TypeString, value)
		_node.ExitImageURL = value
	}
	if value, ok := _c.mutation.ExitLaneID(); ok {
		_spec.SetField(parkingrecord.FieldExitLaneID, field.TypeUUID, value)
		_node.ExitLaneID = &value
	}
	if value, ok := _c.mutation.ExitDeviceID(); ok {
		_spec.SetField(parkingrecord.FieldExitDeviceID, field.TypeString, value)
		_node.ExitDeviceID = value
	}
	if value, ok := _c.mutation.ParkingDuration(); ok {
		_spec.SetField(parkingrecord.FieldParkingDuration, field.TypeInt, value)
		_node.ParkingDuration = value
	}
	if value, ok := _c.mutation.ExitStatus(); ok {
		_spec.SetField(parkingrecord.FieldExitStatus, field.TypeEnum, value)
		_node.ExitStatus = value
	}
	if value, ok := _c.mutation.PaymentLock(); ok {
		_spec.SetField(parkingrecord.FieldPaymentLock, field.TypeInt, value)
		_node.PaymentLock = value
	}
	if value, ok := _c.mutation.RecordMetadata(); ok {
		_spec.SetField(parkingrecord.FieldRecordMetadata, field.TypeJSON, value)
		_node.RecordMetadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(parkingrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(parkingrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ParkingRecordCreateBulk is the builder for creating many ParkingRecord entities in bulk.
type ParkingRecordCreateBulk struct {
	config
	err      error
	builders []*ParkingRecordCreate
}

// Save creates the ParkingRecord entities in the database.
func (_c *ParkingRecordCreateBulk) Save(ctx context.Context) ([]*ParkingRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ParkingRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ParkingRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ParkingRecordCreateBulk) SaveX(ctx context.Context) []*ParkingRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParkingRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParkingRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
