// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuanyiying/smart-park/internal/device/data/ent/devicealert"
	"github.com/xuanyiying/smart-park/internal/device/data/ent/predicate"
)

// DeviceAlertUpdate is the builder for updating DeviceAlert entities.
type DeviceAlertUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceAlertMutation
}

// Where appends a list predicates to the DeviceAlertUpdate builder.
func (_u *DeviceAlertUpdate) Where(ps ...predicate.DeviceAlert) *DeviceAlertUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlertID sets the "alert_id" field.
func (_u *DeviceAlertUpdate) SetAlertID(v string) *DeviceAlertUpdate {
	_u.mutation.SetAlertID(v)
	return _u
}

// SetNillableAlertID sets the "alert_id" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableAlertID(v *string) *DeviceAlertUpdate {
	if v != nil {
		_u.SetAlertID(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceAlertUpdate) SetDeviceID(v string) *DeviceAlertUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableDeviceID(v *string) *DeviceAlertUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DeviceAlertUpdate) SetType(v string) *DeviceAlertUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableType(v *string) *DeviceAlertUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *DeviceAlertUpdate) SetSeverity(v string) *DeviceAlertUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableSeverity(v *string) *DeviceAlertUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *DeviceAlertUpdate) SetMessage(v string) *DeviceAlertUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableMessage(v *string) *DeviceAlertUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceAlertUpdate) SetStatus(v string) *DeviceAlertUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableStatus(v *string) *DeviceAlertUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceAlertUpdate) SetCreatedAt(v time.Time) *DeviceAlertUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableCreatedAt(v *time.Time) *DeviceAlertUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAcknowledgedAt sets the "acknowledged_at" field.
func (_u *DeviceAlertUpdate) SetAcknowledgedAt(v time.Time) *DeviceAlertUpdate {
	_u.mutation.SetAcknowledgedAt(v)
	return _u
}

// SetNillableAcknowledgedAt sets the "acknowledged_at" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableAcknowledgedAt(v *time.Time) *DeviceAlertUpdate {
	if v != nil {
		_u.SetAcknowledgedAt(*v)
	}
	return _u
}

// ClearAcknowledgedAt clears the value of the "acknowledged_at" field.
func (_u *DeviceAlertUpdate) ClearAcknowledgedAt() *DeviceAlertUpdate {
	_u.mutation.ClearAcknowledgedAt()
	return _u
}

// SetAcknowledgedBy sets the "acknowledged_by" field.
func (_u *DeviceAlertUpdate) SetAcknowledgedBy(v string) *DeviceAlertUpdate {
	_u.mutation.SetAcknowledgedBy(v)
	return _u
}

// SetNillableAcknowledgedBy sets the "acknowledged_by" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableAcknowledgedBy(v *string) *DeviceAlertUpdate {
	if v != nil {
		_u.SetAcknowledgedBy(*v)
	}
	return _u
}

// ClearAcknowledgedBy clears the value of the "acknowledged_by" field.
func (_u *DeviceAlertUpdate) ClearAcknowledgedBy() *DeviceAlertUpdate {
	_u.mutation.ClearAcknowledgedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *DeviceAlertUpdate) SetNotes(v string) *DeviceAlertUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *DeviceAlertUpdate) SetNillableNotes(v *string) *DeviceAlertUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *DeviceAlertUpdate) ClearNotes() *DeviceAlertUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DeviceAlertUpdate) SetMetadata(v map[string]string) *DeviceAlertUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DeviceAlertUpdate) ClearMetadata() *DeviceAlertUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the DeviceAlertMutation object of the builder.
func (_u *DeviceAlertUpdate) Mutation() *DeviceAlertMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceAlertUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceAlertUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceAlertUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceAlertUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceAlertUpdate) check() error {
	if v, ok := _u.mutation.AlertID(); ok {
		if err := devicealert.AlertIDValidator(v); err != nil {
			return &ValidationError{Name: "alert_id", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.alert_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := devicealert.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := devicealert.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := devicealert.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := devicealert.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.message": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceAlertUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicealert.Table, devicealert.Columns, sqlgraph.NewFieldSpec(devicealert.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AlertID(); ok {
		_spec.SetField(devicealert.FieldAlertID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(devicealert.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(devicealert.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(devicealert.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(devicealert.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(devicealert.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(devicealert.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AcknowledgedAt(); ok {
		_spec.SetField(devicealert.FieldAcknowledgedAt, field.TypeTime, value)
	}
	if _u.mutation.AcknowledgedAtCleared() {
		_spec.ClearField(devicealert.FieldAcknowledgedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AcknowledgedBy(); ok {
		_spec.SetField(devicealert.FieldAcknowledgedBy, field.TypeString, value)
	}
	if _u.mutation.AcknowledgedByCleared() {
		_spec.ClearField(devicealert.FieldAcknowledgedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(devicealert.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(devicealert.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(devicealert.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(devicealert.FieldMetadata, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicealert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceAlertUpdateOne is the builder for updating a single DeviceAlert entity.
type DeviceAlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceAlertMutation
}

// SetAlertID sets the "alert_id" field.
func (_u *DeviceAlertUpdateOne) SetAlertID(v string) *DeviceAlertUpdateOne {
	_u.mutation.SetAlertID(v)
	return _u
}

// SetNillableAlertID sets the "alert_id" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableAlertID(v *string) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetAlertID(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceAlertUpdateOne) SetDeviceID(v string) *DeviceAlertUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableDeviceID(v *string) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DeviceAlertUpdateOne) SetType(v string) *DeviceAlertUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableType(v *string) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *DeviceAlertUpdateOne) SetSeverity(v string) *DeviceAlertUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableSeverity(v *string) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *DeviceAlertUpdateOne) SetMessage(v string) *DeviceAlertUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableMessage(v *string) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceAlertUpdateOne) SetStatus(v string) *DeviceAlertUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableStatus(v *string) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceAlertUpdateOne) SetCreatedAt(v time.Time) *DeviceAlertUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableCreatedAt(v *time.Time) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAcknowledgedAt sets the "acknowledged_at" field.
func (_u *DeviceAlertUpdateOne) SetAcknowledgedAt(v time.Time) *DeviceAlertUpdateOne {
	_u.mutation.SetAcknowledgedAt(v)
	return _u
}

// SetNillableAcknowledgedAt sets the "acknowledged_at" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableAcknowledgedAt(v *time.Time) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetAcknowledgedAt(*v)
	}
	return _u
}

// ClearAcknowledgedAt clears the value of the "acknowledged_at" field.
func (_u *DeviceAlertUpdateOne) ClearAcknowledgedAt() *DeviceAlertUpdateOne {
	_u.mutation.ClearAcknowledgedAt()
	return _u
}

// SetAcknowledgedBy sets the "acknowledged_by" field.
func (_u *DeviceAlertUpdateOne) SetAcknowledgedBy(v string) *DeviceAlertUpdateOne {
	_u.mutation.SetAcknowledgedBy(v)
	return _u
}

// SetNillableAcknowledgedBy sets the "acknowledged_by" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableAcknowledgedBy(v *string) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetAcknowledgedBy(*v)
	}
	return _u
}

// ClearAcknowledgedBy clears the value of the "acknowledged_by" field.
func (_u *DeviceAlertUpdateOne) ClearAcknowledgedBy() *DeviceAlertUpdateOne {
	_u.mutation.ClearAcknowledgedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *DeviceAlertUpdateOne) SetNotes(v string) *DeviceAlertUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *DeviceAlertUpdateOne) SetNillableNotes(v *string) *DeviceAlertUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *DeviceAlertUpdateOne) ClearNotes() *DeviceAlertUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DeviceAlertUpdateOne) SetMetadata(v map[string]string) *DeviceAlertUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DeviceAlertUpdateOne) ClearMetadata() *DeviceAlertUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the DeviceAlertMutation object of the builder.
func (_u *DeviceAlertUpdateOne) Mutation() *DeviceAlertMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeviceAlertUpdate builder.
func (_u *DeviceAlertUpdateOne) Where(ps ...predicate.DeviceAlert) *DeviceAlertUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceAlertUpdateOne) Select(field string, fields ...string) *DeviceAlertUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeviceAlert entity.
func (_u *DeviceAlertUpdateOne) Save(ctx context.Context) (*DeviceAlert, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceAlertUpdateOne) SaveX(ctx context.Context) *DeviceAlert {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceAlertUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceAlertUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceAlertUpdateOne) check() error {
	if v, ok := _u.mutation.AlertID(); ok {
		if err := devicealert.AlertIDValidator(v); err != nil {
			return &ValidationError{Name: "alert_id", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.alert_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := devicealert.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := devicealert.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := devicealert.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := devicealert.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "DeviceAlert.message": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceAlertUpdateOne) sqlSave(ctx context.Context) (_node *DeviceAlert, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicealert.Table, devicealert.Columns, sqlgraph.NewFieldSpec(devicealert.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeviceAlert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicealert.FieldID)
		for _, f := range fields {
			if !devicealert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != devicealert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AlertID(); ok {
		_spec.SetField(devicealert.FieldAlertID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(devicealert.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(devicealert.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(devicealert.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(devicealert.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(devicealert.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(devicealert.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AcknowledgedAt(); ok {
		_spec.SetField(devicealert.FieldAcknowledgedAt, field.TypeTime, value)
	}
	if _u.mutation.AcknowledgedAtCleared() {
		_spec.ClearField(devicealert.FieldAcknowledgedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AcknowledgedBy(); ok {
		_spec.SetField(devicealert.FieldAcknowledgedBy, field.TypeString, value)
	}
	if _u.mutation.AcknowledgedByCleared() {
		_spec.ClearField(devicealert.FieldAcknowledgedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(devicealert.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(devicealert.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(devicealert.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(devicealert.FieldMetadata, field.TypeJSON)
	}
	_node = &DeviceAlert{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicealert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
