// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuanyiying/smart-park/internal/device/data/ent/device"
	"github.com/xuanyiying/smart-park/internal/device/data/ent/predicate"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceUpdate) SetDeviceID(v string) *DeviceUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *DeviceUpdate) SetDeviceType(v string) *DeviceUpdate {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceType(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdate) SetStatus(v string) *DeviceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableStatus(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOnline sets the "online" field.
func (_u *DeviceUpdate) SetOnline(v bool) *DeviceUpdate {
	_u.mutation.SetOnline(v)
	return _u
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableOnline(v *bool) *DeviceUpdate {
	if v != nil {
		_u.SetOnline(*v)
	}
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *DeviceUpdate) SetLastHeartbeat(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastHeartbeat(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (_u *DeviceUpdate) ClearLastHeartbeat() *DeviceUpdate {
	_u.mutation.ClearLastHeartbeat()
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *DeviceUpdate) SetLotID(v string) *DeviceUpdate {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLotID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// ClearLotID clears the value of the "lot_id" field.
func (_u *DeviceUpdate) ClearLotID() *DeviceUpdate {
	_u.mutation.ClearLotID()
	return _u
}

// SetLaneID sets the "lane_id" field.
func (_u *DeviceUpdate) SetLaneID(v string) *DeviceUpdate {
	_u.mutation.SetLaneID(v)
	return _u
}

// SetNillableLaneID sets the "lane_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLaneID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetLaneID(*v)
	}
	return _u
}

// ClearLaneID clears the value of the "lane_id" field.
func (_u *DeviceUpdate) ClearLaneID() *DeviceUpdate {
	_u.mutation.ClearLaneID()
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *DeviceUpdate) SetProtocol(v string) *DeviceUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableProtocol(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *DeviceUpdate) SetConfig(v map[string]string) *DeviceUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *DeviceUpdate) ClearConfig() *DeviceUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetFirmwareVersion sets the "firmware_version" field.
func (_u *DeviceUpdate) SetFirmwareVersion(v string) *DeviceUpdate {
	_u.mutation.SetFirmwareVersion(v)
	return _u
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableFirmwareVersion(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetFirmwareVersion(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceUpdate) SetCreatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableCreatedAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := device.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Device.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceType(); ok {
		if err := device.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Device.device_type": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(device.FieldDeviceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Online(); ok {
		_spec.SetField(device.FieldOnline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(device.FieldLastHeartbeat, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatCleared() {
		_spec.ClearField(device.FieldLastHeartbeat, field.TypeTime)
	}
	if value, ok := _u.mutation.LotID(); ok {
		_spec.SetField(device.FieldLotID, field.TypeString, value)
	}
	if _u.mutation.LotIDCleared() {
		_spec.ClearField(device.FieldLotID, field.TypeString)
	}
	if value, ok := _u.mutation.LaneID(); ok {
		_spec.SetField(device.FieldLaneID, field.TypeString, value)
	}
	if _u.mutation.LaneIDCleared() {
		_spec.ClearField(device.FieldLaneID, field.TypeString)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(device.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(device.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(device.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.FirmwareVersion(); ok {
		_spec.SetField(device.FieldFirmwareVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceUpdateOne) SetDeviceID(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *DeviceUpdateOne) SetDeviceType(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceType(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdateOne) SetStatus(v string) *DeviceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableStatus(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOnline sets the "online" field.
func (_u *DeviceUpdateOne) SetOnline(v bool) *DeviceUpdateOne {
	_u.mutation.SetOnline(v)
	return _u
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableOnline(v *bool) *DeviceUpdateOne {
	if v != nil {
		_u.SetOnline(*v)
	}
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *DeviceUpdateOne) SetLastHeartbeat(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastHeartbeat(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (_u *DeviceUpdateOne) ClearLastHeartbeat() *DeviceUpdateOne {
	_u.mutation.ClearLastHeartbeat()
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *DeviceUpdateOne) SetLotID(v string) *DeviceUpdateOne {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLotID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// ClearLotID clears the value of the "lot_id" field.
func (_u *DeviceUpdateOne) ClearLotID() *DeviceUpdateOne {
	_u.mutation.ClearLotID()
	return _u
}

// SetLaneID sets the "lane_id" field.
func (_u *DeviceUpdateOne) SetLaneID(v string) *DeviceUpdateOne {
	_u.mutation.SetLaneID(v)
	return _u
}

// SetNillableLaneID sets the "lane_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLaneID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetLaneID(*v)
	}
	return _u
}

// ClearLaneID clears the value of the "lane_id" field.
func (_u *DeviceUpdateOne) ClearLaneID() *DeviceUpdateOne {
	_u.mutation.ClearLaneID()
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *DeviceUpdateOne) SetProtocol(v string) *DeviceUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableProtocol(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *DeviceUpdateOne) SetConfig(v map[string]string) *DeviceUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *DeviceUpdateOne) ClearConfig() *DeviceUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetFirmwareVersion sets the "firmware_version" field.
func (_u *DeviceUpdateOne) SetFirmwareVersion(v string) *DeviceUpdateOne {
	_u.mutation.SetFirmwareVersion(v)
	return _u
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableFirmwareVersion(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetFirmwareVersion(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceUpdateOne) SetCreatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableCreatedAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := device.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Device.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceType(); ok {
		if err := device.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Device.device_type": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(device.FieldDeviceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Online(); ok {
		_spec.SetField(device.FieldOnline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(device.FieldLastHeartbeat, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatCleared() {
		_spec.ClearField(device.FieldLastHeartbeat, field.TypeTime)
	}
	if value, ok := _u.mutation.LotID(); ok {
		_spec.SetField(device.FieldLotID, field.TypeString, value)
	}
	if _u.mutation.LotIDCleared() {
		_spec.ClearField(device.FieldLotID, field.TypeString)
	}
	if value, ok := _u.mutation.LaneID(); ok {
		_spec.SetField(device.FieldLaneID, field.TypeString, value)
	}
	if _u.mutation.LaneIDCleared() {
		_spec.ClearField(device.FieldLaneID, field.TypeString)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(device.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(device.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(device.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.FirmwareVersion(); ok {
		_spec.SetField(device.FieldFirmwareVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
