// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/user/data/ent/uservehicle"
)

// UserVehicle is the model entity for the UserVehicle schema.
type UserVehicle struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 用户ID
	UserID uuid.UUID `json:"user_id,omitempty"`
	// 车牌号
	PlateNumber string `json:"plate_number,omitempty"`
	// 车主姓名
	OwnerName string `json:"owner_name,omitempty"`
	// 车主电话
	OwnerPhone string `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserVehicle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uservehicle.FieldPlateNumber, uservehicle.FieldOwnerName, uservehicle.FieldOwnerPhone:
			values[i] = new(sql.NullString)
		case uservehicle.FieldCreatedAt, uservehicle.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case uservehicle.FieldID, uservehicle.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserVehicle fields.
func (_m *UserVehicle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uservehicle.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uservehicle.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case uservehicle.FieldPlateNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plate_number", values[i])
			} else if value.Valid {
				_m.PlateNumber = value.String
			}
		case uservehicle.FieldOwnerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_name", values[i])
			} else if value.Valid {
				_m.OwnerName = value.String
			}
		case uservehicle.FieldOwnerPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_phone", values[i])
			} else if value.Valid {
				_m.OwnerPhone = value.String
			}
		case uservehicle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case uservehicle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserVehicle.
// This includes values selected through modifiers, order, etc.
func (_m *UserVehicle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserVehicle.
// Note that you need to call UserVehicle.Unwrap() before calling this method if this UserVehicle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserVehicle) Update() *UserVehicleUpdateOne {
	return NewUserVehicleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserVehicle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserVehicle) Unwrap() *UserVehicle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserVehicle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserVehicle) String() string {
	var builder strings.Builder
	builder.WriteString("UserVehicle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("plate_number=")
	builder.WriteString(_m.PlateNumber)
	builder.WriteString(", ")
	builder.WriteString("owner_name=")
	builder.WriteString(_m.OwnerName)
	builder.WriteString(", ")
	builder.WriteString("owner_phone=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserVehicles is a parsable slice of UserVehicle.
type UserVehicles []*UserVehicle
