// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BillingRule is the predicate function for billingrule builders.
type BillingRule func(*sql.Selector)
