server:
  port: 8000
  timeout: 60

routes:
  - path: /api/v1/device
    target: localhost:8001
  - path: /api/v1/billing
    target: localhost:8002
  - path: /api/v1/pay
    target: localhost:8003
  - path: /api/v1/admin/billing
    target: localhost:8002
  - path: /api/v1/admin
    target: localhost:8004
  - path: /api/v1/user
    target: localhost:8005

# JWT 认证配置
jwt:
  public_key_path: "./keys/public.pem"
  # 跳过认证的路径 (可选)
  skip_paths:
    - "/health"
    - "/ready"
    - "/api/v1/user/login"
    - "/api/v1/user/register"

etcd:
  endpoints:
    - "localhost:2380"
  timeout: 5s

log:
  level: info
  format: json

otel:
  endpoint: "localhost:4317"
  serviceName: "gateway-svc"
