server:
  port: 8000
  timeout: 60

routes:
  - path: /api/v1/device
    target: localhost:8001
  - path: /api/v1/billing
    target: localhost:8002
  - path: /api/v1/pay
    target: localhost:8003
  - path: /api/v1/admin
    target: localhost:8004
  - path: /api/v1/user
    target: localhost:8005

etcd:
  endpoints:
    - "localhost:2379"
  timeout: 5s

log:
  level: info
  format: json

otel:
  endpoint: "localhost:4317"
  serviceName: "gateway-svc"
