// Code generated by ent, DO NOT EDIT.

package parkingspace

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the parkingspace type in the database.
	Label = "parking_space"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpaceID holds the string denoting the space_id field in the database.
	FieldSpaceID = "space_id"
	// FieldLotID holds the string denoting the lot_id field in the database.
	FieldLotID = "lot_id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVehiclePlate holds the string denoting the vehicle_plate field in the database.
	FieldVehiclePlate = "vehicle_plate"
	// FieldLastUpdate holds the string denoting the last_update field in the database.
	FieldLastUpdate = "last_update"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the parkingspace in the database.
	Table = "parking_spaces"
)

// Columns holds all SQL columns for parkingspace fields.
var Columns = []string{
	FieldID,
	FieldSpaceID,
	FieldLotID,
	FieldDeviceID,
	FieldStatus,
	FieldVehiclePlate,
	FieldLastUpdate,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SpaceIDValidator is a validator for the "space_id" field. It is called by the builders before save.
	SpaceIDValidator func(string) error
	// DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	DeviceIDValidator func(string) error
	// VehiclePlateValidator is a validator for the "vehicle_plate" field. It is called by the builders before save.
	VehiclePlateValidator func(string) error
	// DefaultLastUpdate holds the default value on creation for the "last_update" field.
	DefaultLastUpdate func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusAvailable is the default value of the Status enum.
const DefaultStatus = StatusAvailable

// Status values.
const (
	StatusAvailable   Status = "available"
	StatusOccupied    Status = "occupied"
	StatusReserved    Status = "reserved"
	StatusMaintenance Status = "maintenance"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAvailable, StatusOccupied, StatusReserved, StatusMaintenance:
		return nil
	default:
		return fmt.Errorf("parkingspace: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ParkingSpace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySpaceID orders the results by the space_id field.
func BySpaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpaceID, opts...).ToFunc()
}

// ByLotID orders the results by the lot_id field.
func ByLotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLotID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVehiclePlate orders the results by the vehicle_plate field.
func ByVehiclePlate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVehiclePlate, opts...).ToFunc()
}

// ByLastUpdate orders the results by the last_update field.
func ByLastUpdate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
