// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/billingrule"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/device"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/devicefault"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/devicelog"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/deviceperformance"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/deviceupgrade"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/firmware"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/lane"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/manufacturer"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/offlinesyncrecord"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/parkingrecord"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/vehicle"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BillingRule is the client for interacting with the BillingRule builders.
	BillingRule *BillingRuleClient
	// Device is the client for interacting with the Device builders.
	Device *DeviceClient
	// DeviceFault is the client for interacting with the DeviceFault builders.
	DeviceFault *DeviceFaultClient
	// DeviceLog is the client for interacting with the DeviceLog builders.
	DeviceLog *DeviceLogClient
	// DevicePerformance is the client for interacting with the DevicePerformance builders.
	DevicePerformance *DevicePerformanceClient
	// DeviceUpgrade is the client for interacting with the DeviceUpgrade builders.
	DeviceUpgrade *DeviceUpgradeClient
	// Firmware is the client for interacting with the Firmware builders.
	Firmware *FirmwareClient
	// Lane is the client for interacting with the Lane builders.
	Lane *LaneClient
	// Manufacturer is the client for interacting with the Manufacturer builders.
	Manufacturer *ManufacturerClient
	// OfflineSyncRecord is the client for interacting with the OfflineSyncRecord builders.
	OfflineSyncRecord *OfflineSyncRecordClient
	// ParkingRecord is the client for interacting with the ParkingRecord builders.
	ParkingRecord *ParkingRecordClient
	// Vehicle is the client for interacting with the Vehicle builders.
	Vehicle *VehicleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BillingRule = NewBillingRuleClient(c.config)
	c.Device = NewDeviceClient(c.config)
	c.DeviceFault = NewDeviceFaultClient(c.config)
	c.DeviceLog = NewDeviceLogClient(c.config)
	c.DevicePerformance = NewDevicePerformanceClient(c.config)
	c.DeviceUpgrade = NewDeviceUpgradeClient(c.config)
	c.Firmware = NewFirmwareClient(c.config)
	c.Lane = NewLaneClient(c.config)
	c.Manufacturer = NewManufacturerClient(c.config)
	c.OfflineSyncRecord = NewOfflineSyncRecordClient(c.config)
	c.ParkingRecord = NewParkingRecordClient(c.config)
	c.Vehicle = NewVehicleClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		BillingRule:       NewBillingRuleClient(cfg),
		Device:            NewDeviceClient(cfg),
		DeviceFault:       NewDeviceFaultClient(cfg),
		DeviceLog:         NewDeviceLogClient(cfg),
		DevicePerformance: NewDevicePerformanceClient(cfg),
		DeviceUpgrade:     NewDeviceUpgradeClient(cfg),
		Firmware:          NewFirmwareClient(cfg),
		Lane:              NewLaneClient(cfg),
		Manufacturer:      NewManufacturerClient(cfg),
		OfflineSyncRecord: NewOfflineSyncRecordClient(cfg),
		ParkingRecord:     NewParkingRecordClient(cfg),
		Vehicle:           NewVehicleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		BillingRule:       NewBillingRuleClient(cfg),
		Device:            NewDeviceClient(cfg),
		DeviceFault:       NewDeviceFaultClient(cfg),
		DeviceLog:         NewDeviceLogClient(cfg),
		DevicePerformance: NewDevicePerformanceClient(cfg),
		DeviceUpgrade:     NewDeviceUpgradeClient(cfg),
		Firmware:          NewFirmwareClient(cfg),
		Lane:              NewLaneClient(cfg),
		Manufacturer:      NewManufacturerClient(cfg),
		OfflineSyncRecord: NewOfflineSyncRecordClient(cfg),
		ParkingRecord:     NewParkingRecordClient(cfg),
		Vehicle:           NewVehicleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BillingRule.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.BillingRule, c.Device, c.DeviceFault, c.DeviceLog, c.DevicePerformance,
		c.DeviceUpgrade, c.Firmware, c.Lane, c.Manufacturer, c.OfflineSyncRecord,
		c.ParkingRecord, c.Vehicle,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.BillingRule, c.Device, c.DeviceFault, c.DeviceLog, c.DevicePerformance,
		c.DeviceUpgrade, c.Firmware, c.Lane, c.Manufacturer, c.OfflineSyncRecord,
		c.ParkingRecord, c.Vehicle,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BillingRuleMutation:
		return c.BillingRule.mutate(ctx, m)
	case *DeviceMutation:
		return c.Device.mutate(ctx, m)
	case *DeviceFaultMutation:
		return c.DeviceFault.mutate(ctx, m)
	case *DeviceLogMutation:
		return c.DeviceLog.mutate(ctx, m)
	case *DevicePerformanceMutation:
		return c.DevicePerformance.mutate(ctx, m)
	case *DeviceUpgradeMutation:
		return c.DeviceUpgrade.mutate(ctx, m)
	case *FirmwareMutation:
		return c.Firmware.mutate(ctx, m)
	case *LaneMutation:
		return c.Lane.mutate(ctx, m)
	case *ManufacturerMutation:
		return c.Manufacturer.mutate(ctx, m)
	case *OfflineSyncRecordMutation:
		return c.OfflineSyncRecord.mutate(ctx, m)
	case *ParkingRecordMutation:
		return c.ParkingRecord.mutate(ctx, m)
	case *VehicleMutation:
		return c.Vehicle.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BillingRuleClient is a client for the BillingRule schema.
type BillingRuleClient struct {
	config
}

// NewBillingRuleClient returns a client for the BillingRule from the given config.
func NewBillingRuleClient(c config) *BillingRuleClient {
	return &BillingRuleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `billingrule.Hooks(f(g(h())))`.
func (c *BillingRuleClient) Use(hooks ...Hook) {
	c.hooks.BillingRule = append(c.hooks.BillingRule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `billingrule.Intercept(f(g(h())))`.
func (c *BillingRuleClient) Intercept(interceptors ...Interceptor) {
	c.inters.BillingRule = append(c.inters.BillingRule, interceptors...)
}

// Create returns a builder for creating a BillingRule entity.
func (c *BillingRuleClient) Create() *BillingRuleCreate {
	mutation := newBillingRuleMutation(c.config, OpCreate)
	return &BillingRuleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BillingRule entities.
func (c *BillingRuleClient) CreateBulk(builders ...*BillingRuleCreate) *BillingRuleCreateBulk {
	return &BillingRuleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BillingRuleClient) MapCreateBulk(slice any, setFunc func(*BillingRuleCreate, int)) *BillingRuleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BillingRuleCreateBulk{err: fmt.Errorf("calling to BillingRuleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BillingRuleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BillingRuleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BillingRule.
func (c *BillingRuleClient) Update() *BillingRuleUpdate {
	mutation := newBillingRuleMutation(c.config, OpUpdate)
	return &BillingRuleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BillingRuleClient) UpdateOne(_m *BillingRule) *BillingRuleUpdateOne {
	mutation := newBillingRuleMutation(c.config, OpUpdateOne, withBillingRule(_m))
	return &BillingRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BillingRuleClient) UpdateOneID(id uuid.UUID) *BillingRuleUpdateOne {
	mutation := newBillingRuleMutation(c.config, OpUpdateOne, withBillingRuleID(id))
	return &BillingRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BillingRule.
func (c *BillingRuleClient) Delete() *BillingRuleDelete {
	mutation := newBillingRuleMutation(c.config, OpDelete)
	return &BillingRuleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BillingRuleClient) DeleteOne(_m *BillingRule) *BillingRuleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BillingRuleClient) DeleteOneID(id uuid.UUID) *BillingRuleDeleteOne {
	builder := c.Delete().Where(billingrule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BillingRuleDeleteOne{builder}
}

// Query returns a query builder for BillingRule.
func (c *BillingRuleClient) Query() *BillingRuleQuery {
	return &BillingRuleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBillingRule},
		inters: c.Interceptors(),
	}
}

// Get returns a BillingRule entity by its id.
func (c *BillingRuleClient) Get(ctx context.Context, id uuid.UUID) (*BillingRule, error) {
	return c.Query().Where(billingrule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BillingRuleClient) GetX(ctx context.Context, id uuid.UUID) *BillingRule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BillingRuleClient) Hooks() []Hook {
	return c.hooks.BillingRule
}

// Interceptors returns the client interceptors.
func (c *BillingRuleClient) Interceptors() []Interceptor {
	return c.inters.BillingRule
}

func (c *BillingRuleClient) mutate(ctx context.Context, m *BillingRuleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BillingRuleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BillingRuleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BillingRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BillingRuleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BillingRule mutation op: %q", m.Op())
	}
}

// DeviceClient is a client for the Device schema.
type DeviceClient struct {
	config
}

// NewDeviceClient returns a client for the Device from the given config.
func NewDeviceClient(c config) *DeviceClient {
	return &DeviceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `device.Hooks(f(g(h())))`.
func (c *DeviceClient) Use(hooks ...Hook) {
	c.hooks.Device = append(c.hooks.Device, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `device.Intercept(f(g(h())))`.
func (c *DeviceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Device = append(c.inters.Device, interceptors...)
}

// Create returns a builder for creating a Device entity.
func (c *DeviceClient) Create() *DeviceCreate {
	mutation := newDeviceMutation(c.config, OpCreate)
	return &DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Device entities.
func (c *DeviceClient) CreateBulk(builders ...*DeviceCreate) *DeviceCreateBulk {
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceClient) MapCreateBulk(slice any, setFunc func(*DeviceCreate, int)) *DeviceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceCreateBulk{err: fmt.Errorf("calling to DeviceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Device.
func (c *DeviceClient) Update() *DeviceUpdate {
	mutation := newDeviceMutation(c.config, OpUpdate)
	return &DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceClient) UpdateOne(_m *Device) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDevice(_m))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceClient) UpdateOneID(id uuid.UUID) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDeviceID(id))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Device.
func (c *DeviceClient) Delete() *DeviceDelete {
	mutation := newDeviceMutation(c.config, OpDelete)
	return &DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceClient) DeleteOne(_m *Device) *DeviceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceClient) DeleteOneID(id uuid.UUID) *DeviceDeleteOne {
	builder := c.Delete().Where(device.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceDeleteOne{builder}
}

// Query returns a query builder for Device.
func (c *DeviceClient) Query() *DeviceQuery {
	return &DeviceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDevice},
		inters: c.Interceptors(),
	}
}

// Get returns a Device entity by its id.
func (c *DeviceClient) Get(ctx context.Context, id uuid.UUID) (*Device, error) {
	return c.Query().Where(device.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceClient) GetX(ctx context.Context, id uuid.UUID) *Device {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceClient) Hooks() []Hook {
	return c.hooks.Device
}

// Interceptors returns the client interceptors.
func (c *DeviceClient) Interceptors() []Interceptor {
	return c.inters.Device
}

func (c *DeviceClient) mutate(ctx context.Context, m *DeviceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Device mutation op: %q", m.Op())
	}
}

// DeviceFaultClient is a client for the DeviceFault schema.
type DeviceFaultClient struct {
	config
}

// NewDeviceFaultClient returns a client for the DeviceFault from the given config.
func NewDeviceFaultClient(c config) *DeviceFaultClient {
	return &DeviceFaultClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `devicefault.Hooks(f(g(h())))`.
func (c *DeviceFaultClient) Use(hooks ...Hook) {
	c.hooks.DeviceFault = append(c.hooks.DeviceFault, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `devicefault.Intercept(f(g(h())))`.
func (c *DeviceFaultClient) Intercept(interceptors ...Interceptor) {
	c.inters.DeviceFault = append(c.inters.DeviceFault, interceptors...)
}

// Create returns a builder for creating a DeviceFault entity.
func (c *DeviceFaultClient) Create() *DeviceFaultCreate {
	mutation := newDeviceFaultMutation(c.config, OpCreate)
	return &DeviceFaultCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DeviceFault entities.
func (c *DeviceFaultClient) CreateBulk(builders ...*DeviceFaultCreate) *DeviceFaultCreateBulk {
	return &DeviceFaultCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceFaultClient) MapCreateBulk(slice any, setFunc func(*DeviceFaultCreate, int)) *DeviceFaultCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceFaultCreateBulk{err: fmt.Errorf("calling to DeviceFaultClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceFaultCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceFaultCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DeviceFault.
func (c *DeviceFaultClient) Update() *DeviceFaultUpdate {
	mutation := newDeviceFaultMutation(c.config, OpUpdate)
	return &DeviceFaultUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceFaultClient) UpdateOne(_m *DeviceFault) *DeviceFaultUpdateOne {
	mutation := newDeviceFaultMutation(c.config, OpUpdateOne, withDeviceFault(_m))
	return &DeviceFaultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceFaultClient) UpdateOneID(id uuid.UUID) *DeviceFaultUpdateOne {
	mutation := newDeviceFaultMutation(c.config, OpUpdateOne, withDeviceFaultID(id))
	return &DeviceFaultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DeviceFault.
func (c *DeviceFaultClient) Delete() *DeviceFaultDelete {
	mutation := newDeviceFaultMutation(c.config, OpDelete)
	return &DeviceFaultDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceFaultClient) DeleteOne(_m *DeviceFault) *DeviceFaultDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceFaultClient) DeleteOneID(id uuid.UUID) *DeviceFaultDeleteOne {
	builder := c.Delete().Where(devicefault.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceFaultDeleteOne{builder}
}

// Query returns a query builder for DeviceFault.
func (c *DeviceFaultClient) Query() *DeviceFaultQuery {
	return &DeviceFaultQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeviceFault},
		inters: c.Interceptors(),
	}
}

// Get returns a DeviceFault entity by its id.
func (c *DeviceFaultClient) Get(ctx context.Context, id uuid.UUID) (*DeviceFault, error) {
	return c.Query().Where(devicefault.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceFaultClient) GetX(ctx context.Context, id uuid.UUID) *DeviceFault {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceFaultClient) Hooks() []Hook {
	return c.hooks.DeviceFault
}

// Interceptors returns the client interceptors.
func (c *DeviceFaultClient) Interceptors() []Interceptor {
	return c.inters.DeviceFault
}

func (c *DeviceFaultClient) mutate(ctx context.Context, m *DeviceFaultMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceFaultCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceFaultUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceFaultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceFaultDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DeviceFault mutation op: %q", m.Op())
	}
}

// DeviceLogClient is a client for the DeviceLog schema.
type DeviceLogClient struct {
	config
}

// NewDeviceLogClient returns a client for the DeviceLog from the given config.
func NewDeviceLogClient(c config) *DeviceLogClient {
	return &DeviceLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `devicelog.Hooks(f(g(h())))`.
func (c *DeviceLogClient) Use(hooks ...Hook) {
	c.hooks.DeviceLog = append(c.hooks.DeviceLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `devicelog.Intercept(f(g(h())))`.
func (c *DeviceLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.DeviceLog = append(c.inters.DeviceLog, interceptors...)
}

// Create returns a builder for creating a DeviceLog entity.
func (c *DeviceLogClient) Create() *DeviceLogCreate {
	mutation := newDeviceLogMutation(c.config, OpCreate)
	return &DeviceLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DeviceLog entities.
func (c *DeviceLogClient) CreateBulk(builders ...*DeviceLogCreate) *DeviceLogCreateBulk {
	return &DeviceLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceLogClient) MapCreateBulk(slice any, setFunc func(*DeviceLogCreate, int)) *DeviceLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceLogCreateBulk{err: fmt.Errorf("calling to DeviceLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DeviceLog.
func (c *DeviceLogClient) Update() *DeviceLogUpdate {
	mutation := newDeviceLogMutation(c.config, OpUpdate)
	return &DeviceLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceLogClient) UpdateOne(_m *DeviceLog) *DeviceLogUpdateOne {
	mutation := newDeviceLogMutation(c.config, OpUpdateOne, withDeviceLog(_m))
	return &DeviceLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceLogClient) UpdateOneID(id uuid.UUID) *DeviceLogUpdateOne {
	mutation := newDeviceLogMutation(c.config, OpUpdateOne, withDeviceLogID(id))
	return &DeviceLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DeviceLog.
func (c *DeviceLogClient) Delete() *DeviceLogDelete {
	mutation := newDeviceLogMutation(c.config, OpDelete)
	return &DeviceLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceLogClient) DeleteOne(_m *DeviceLog) *DeviceLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceLogClient) DeleteOneID(id uuid.UUID) *DeviceLogDeleteOne {
	builder := c.Delete().Where(devicelog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceLogDeleteOne{builder}
}

// Query returns a query builder for DeviceLog.
func (c *DeviceLogClient) Query() *DeviceLogQuery {
	return &DeviceLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeviceLog},
		inters: c.Interceptors(),
	}
}

// Get returns a DeviceLog entity by its id.
func (c *DeviceLogClient) Get(ctx context.Context, id uuid.UUID) (*DeviceLog, error) {
	return c.Query().Where(devicelog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceLogClient) GetX(ctx context.Context, id uuid.UUID) *DeviceLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceLogClient) Hooks() []Hook {
	return c.hooks.DeviceLog
}

// Interceptors returns the client interceptors.
func (c *DeviceLogClient) Interceptors() []Interceptor {
	return c.inters.DeviceLog
}

func (c *DeviceLogClient) mutate(ctx context.Context, m *DeviceLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DeviceLog mutation op: %q", m.Op())
	}
}

// DevicePerformanceClient is a client for the DevicePerformance schema.
type DevicePerformanceClient struct {
	config
}

// NewDevicePerformanceClient returns a client for the DevicePerformance from the given config.
func NewDevicePerformanceClient(c config) *DevicePerformanceClient {
	return &DevicePerformanceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `deviceperformance.Hooks(f(g(h())))`.
func (c *DevicePerformanceClient) Use(hooks ...Hook) {
	c.hooks.DevicePerformance = append(c.hooks.DevicePerformance, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `deviceperformance.Intercept(f(g(h())))`.
func (c *DevicePerformanceClient) Intercept(interceptors ...Interceptor) {
	c.inters.DevicePerformance = append(c.inters.DevicePerformance, interceptors...)
}

// Create returns a builder for creating a DevicePerformance entity.
func (c *DevicePerformanceClient) Create() *DevicePerformanceCreate {
	mutation := newDevicePerformanceMutation(c.config, OpCreate)
	return &DevicePerformanceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DevicePerformance entities.
func (c *DevicePerformanceClient) CreateBulk(builders ...*DevicePerformanceCreate) *DevicePerformanceCreateBulk {
	return &DevicePerformanceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DevicePerformanceClient) MapCreateBulk(slice any, setFunc func(*DevicePerformanceCreate, int)) *DevicePerformanceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DevicePerformanceCreateBulk{err: fmt.Errorf("calling to DevicePerformanceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DevicePerformanceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DevicePerformanceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DevicePerformance.
func (c *DevicePerformanceClient) Update() *DevicePerformanceUpdate {
	mutation := newDevicePerformanceMutation(c.config, OpUpdate)
	return &DevicePerformanceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DevicePerformanceClient) UpdateOne(_m *DevicePerformance) *DevicePerformanceUpdateOne {
	mutation := newDevicePerformanceMutation(c.config, OpUpdateOne, withDevicePerformance(_m))
	return &DevicePerformanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DevicePerformanceClient) UpdateOneID(id uuid.UUID) *DevicePerformanceUpdateOne {
	mutation := newDevicePerformanceMutation(c.config, OpUpdateOne, withDevicePerformanceID(id))
	return &DevicePerformanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DevicePerformance.
func (c *DevicePerformanceClient) Delete() *DevicePerformanceDelete {
	mutation := newDevicePerformanceMutation(c.config, OpDelete)
	return &DevicePerformanceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DevicePerformanceClient) DeleteOne(_m *DevicePerformance) *DevicePerformanceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DevicePerformanceClient) DeleteOneID(id uuid.UUID) *DevicePerformanceDeleteOne {
	builder := c.Delete().Where(deviceperformance.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DevicePerformanceDeleteOne{builder}
}

// Query returns a query builder for DevicePerformance.
func (c *DevicePerformanceClient) Query() *DevicePerformanceQuery {
	return &DevicePerformanceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDevicePerformance},
		inters: c.Interceptors(),
	}
}

// Get returns a DevicePerformance entity by its id.
func (c *DevicePerformanceClient) Get(ctx context.Context, id uuid.UUID) (*DevicePerformance, error) {
	return c.Query().Where(deviceperformance.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DevicePerformanceClient) GetX(ctx context.Context, id uuid.UUID) *DevicePerformance {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DevicePerformanceClient) Hooks() []Hook {
	return c.hooks.DevicePerformance
}

// Interceptors returns the client interceptors.
func (c *DevicePerformanceClient) Interceptors() []Interceptor {
	return c.inters.DevicePerformance
}

func (c *DevicePerformanceClient) mutate(ctx context.Context, m *DevicePerformanceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DevicePerformanceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DevicePerformanceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DevicePerformanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DevicePerformanceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DevicePerformance mutation op: %q", m.Op())
	}
}

// DeviceUpgradeClient is a client for the DeviceUpgrade schema.
type DeviceUpgradeClient struct {
	config
}

// NewDeviceUpgradeClient returns a client for the DeviceUpgrade from the given config.
func NewDeviceUpgradeClient(c config) *DeviceUpgradeClient {
	return &DeviceUpgradeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `deviceupgrade.Hooks(f(g(h())))`.
func (c *DeviceUpgradeClient) Use(hooks ...Hook) {
	c.hooks.DeviceUpgrade = append(c.hooks.DeviceUpgrade, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `deviceupgrade.Intercept(f(g(h())))`.
func (c *DeviceUpgradeClient) Intercept(interceptors ...Interceptor) {
	c.inters.DeviceUpgrade = append(c.inters.DeviceUpgrade, interceptors...)
}

// Create returns a builder for creating a DeviceUpgrade entity.
func (c *DeviceUpgradeClient) Create() *DeviceUpgradeCreate {
	mutation := newDeviceUpgradeMutation(c.config, OpCreate)
	return &DeviceUpgradeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DeviceUpgrade entities.
func (c *DeviceUpgradeClient) CreateBulk(builders ...*DeviceUpgradeCreate) *DeviceUpgradeCreateBulk {
	return &DeviceUpgradeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceUpgradeClient) MapCreateBulk(slice any, setFunc func(*DeviceUpgradeCreate, int)) *DeviceUpgradeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceUpgradeCreateBulk{err: fmt.Errorf("calling to DeviceUpgradeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceUpgradeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceUpgradeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DeviceUpgrade.
func (c *DeviceUpgradeClient) Update() *DeviceUpgradeUpdate {
	mutation := newDeviceUpgradeMutation(c.config, OpUpdate)
	return &DeviceUpgradeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceUpgradeClient) UpdateOne(_m *DeviceUpgrade) *DeviceUpgradeUpdateOne {
	mutation := newDeviceUpgradeMutation(c.config, OpUpdateOne, withDeviceUpgrade(_m))
	return &DeviceUpgradeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceUpgradeClient) UpdateOneID(id uuid.UUID) *DeviceUpgradeUpdateOne {
	mutation := newDeviceUpgradeMutation(c.config, OpUpdateOne, withDeviceUpgradeID(id))
	return &DeviceUpgradeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DeviceUpgrade.
func (c *DeviceUpgradeClient) Delete() *DeviceUpgradeDelete {
	mutation := newDeviceUpgradeMutation(c.config, OpDelete)
	return &DeviceUpgradeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceUpgradeClient) DeleteOne(_m *DeviceUpgrade) *DeviceUpgradeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceUpgradeClient) DeleteOneID(id uuid.UUID) *DeviceUpgradeDeleteOne {
	builder := c.Delete().Where(deviceupgrade.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceUpgradeDeleteOne{builder}
}

// Query returns a query builder for DeviceUpgrade.
func (c *DeviceUpgradeClient) Query() *DeviceUpgradeQuery {
	return &DeviceUpgradeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeviceUpgrade},
		inters: c.Interceptors(),
	}
}

// Get returns a DeviceUpgrade entity by its id.
func (c *DeviceUpgradeClient) Get(ctx context.Context, id uuid.UUID) (*DeviceUpgrade, error) {
	return c.Query().Where(deviceupgrade.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceUpgradeClient) GetX(ctx context.Context, id uuid.UUID) *DeviceUpgrade {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceUpgradeClient) Hooks() []Hook {
	return c.hooks.DeviceUpgrade
}

// Interceptors returns the client interceptors.
func (c *DeviceUpgradeClient) Interceptors() []Interceptor {
	return c.inters.DeviceUpgrade
}

func (c *DeviceUpgradeClient) mutate(ctx context.Context, m *DeviceUpgradeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceUpgradeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceUpgradeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceUpgradeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceUpgradeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DeviceUpgrade mutation op: %q", m.Op())
	}
}

// FirmwareClient is a client for the Firmware schema.
type FirmwareClient struct {
	config
}

// NewFirmwareClient returns a client for the Firmware from the given config.
func NewFirmwareClient(c config) *FirmwareClient {
	return &FirmwareClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `firmware.Hooks(f(g(h())))`.
func (c *FirmwareClient) Use(hooks ...Hook) {
	c.hooks.Firmware = append(c.hooks.Firmware, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `firmware.Intercept(f(g(h())))`.
func (c *FirmwareClient) Intercept(interceptors ...Interceptor) {
	c.inters.Firmware = append(c.inters.Firmware, interceptors...)
}

// Create returns a builder for creating a Firmware entity.
func (c *FirmwareClient) Create() *FirmwareCreate {
	mutation := newFirmwareMutation(c.config, OpCreate)
	return &FirmwareCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Firmware entities.
func (c *FirmwareClient) CreateBulk(builders ...*FirmwareCreate) *FirmwareCreateBulk {
	return &FirmwareCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FirmwareClient) MapCreateBulk(slice any, setFunc func(*FirmwareCreate, int)) *FirmwareCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FirmwareCreateBulk{err: fmt.Errorf("calling to FirmwareClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FirmwareCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FirmwareCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Firmware.
func (c *FirmwareClient) Update() *FirmwareUpdate {
	mutation := newFirmwareMutation(c.config, OpUpdate)
	return &FirmwareUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FirmwareClient) UpdateOne(_m *Firmware) *FirmwareUpdateOne {
	mutation := newFirmwareMutation(c.config, OpUpdateOne, withFirmware(_m))
	return &FirmwareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FirmwareClient) UpdateOneID(id uuid.UUID) *FirmwareUpdateOne {
	mutation := newFirmwareMutation(c.config, OpUpdateOne, withFirmwareID(id))
	return &FirmwareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Firmware.
func (c *FirmwareClient) Delete() *FirmwareDelete {
	mutation := newFirmwareMutation(c.config, OpDelete)
	return &FirmwareDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FirmwareClient) DeleteOne(_m *Firmware) *FirmwareDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FirmwareClient) DeleteOneID(id uuid.UUID) *FirmwareDeleteOne {
	builder := c.Delete().Where(firmware.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FirmwareDeleteOne{builder}
}

// Query returns a query builder for Firmware.
func (c *FirmwareClient) Query() *FirmwareQuery {
	return &FirmwareQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFirmware},
		inters: c.Interceptors(),
	}
}

// Get returns a Firmware entity by its id.
func (c *FirmwareClient) Get(ctx context.Context, id uuid.UUID) (*Firmware, error) {
	return c.Query().Where(firmware.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FirmwareClient) GetX(ctx context.Context, id uuid.UUID) *Firmware {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FirmwareClient) Hooks() []Hook {
	return c.hooks.Firmware
}

// Interceptors returns the client interceptors.
func (c *FirmwareClient) Interceptors() []Interceptor {
	return c.inters.Firmware
}

func (c *FirmwareClient) mutate(ctx context.Context, m *FirmwareMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FirmwareCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FirmwareUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FirmwareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FirmwareDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Firmware mutation op: %q", m.Op())
	}
}

// LaneClient is a client for the Lane schema.
type LaneClient struct {
	config
}

// NewLaneClient returns a client for the Lane from the given config.
func NewLaneClient(c config) *LaneClient {
	return &LaneClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lane.Hooks(f(g(h())))`.
func (c *LaneClient) Use(hooks ...Hook) {
	c.hooks.Lane = append(c.hooks.Lane, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `lane.Intercept(f(g(h())))`.
func (c *LaneClient) Intercept(interceptors ...Interceptor) {
	c.inters.Lane = append(c.inters.Lane, interceptors...)
}

// Create returns a builder for creating a Lane entity.
func (c *LaneClient) Create() *LaneCreate {
	mutation := newLaneMutation(c.config, OpCreate)
	return &LaneCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Lane entities.
func (c *LaneClient) CreateBulk(builders ...*LaneCreate) *LaneCreateBulk {
	return &LaneCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LaneClient) MapCreateBulk(slice any, setFunc func(*LaneCreate, int)) *LaneCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LaneCreateBulk{err: fmt.Errorf("calling to LaneClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LaneCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LaneCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Lane.
func (c *LaneClient) Update() *LaneUpdate {
	mutation := newLaneMutation(c.config, OpUpdate)
	return &LaneUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LaneClient) UpdateOne(_m *Lane) *LaneUpdateOne {
	mutation := newLaneMutation(c.config, OpUpdateOne, withLane(_m))
	return &LaneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LaneClient) UpdateOneID(id uuid.UUID) *LaneUpdateOne {
	mutation := newLaneMutation(c.config, OpUpdateOne, withLaneID(id))
	return &LaneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Lane.
func (c *LaneClient) Delete() *LaneDelete {
	mutation := newLaneMutation(c.config, OpDelete)
	return &LaneDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LaneClient) DeleteOne(_m *Lane) *LaneDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LaneClient) DeleteOneID(id uuid.UUID) *LaneDeleteOne {
	builder := c.Delete().Where(lane.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LaneDeleteOne{builder}
}

// Query returns a query builder for Lane.
func (c *LaneClient) Query() *LaneQuery {
	return &LaneQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLane},
		inters: c.Interceptors(),
	}
}

// Get returns a Lane entity by its id.
func (c *LaneClient) Get(ctx context.Context, id uuid.UUID) (*Lane, error) {
	return c.Query().Where(lane.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LaneClient) GetX(ctx context.Context, id uuid.UUID) *Lane {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LaneClient) Hooks() []Hook {
	return c.hooks.Lane
}

// Interceptors returns the client interceptors.
func (c *LaneClient) Interceptors() []Interceptor {
	return c.inters.Lane
}

func (c *LaneClient) mutate(ctx context.Context, m *LaneMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LaneCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LaneUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LaneUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LaneDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Lane mutation op: %q", m.Op())
	}
}

// ManufacturerClient is a client for the Manufacturer schema.
type ManufacturerClient struct {
	config
}

// NewManufacturerClient returns a client for the Manufacturer from the given config.
func NewManufacturerClient(c config) *ManufacturerClient {
	return &ManufacturerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `manufacturer.Hooks(f(g(h())))`.
func (c *ManufacturerClient) Use(hooks ...Hook) {
	c.hooks.Manufacturer = append(c.hooks.Manufacturer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `manufacturer.Intercept(f(g(h())))`.
func (c *ManufacturerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Manufacturer = append(c.inters.Manufacturer, interceptors...)
}

// Create returns a builder for creating a Manufacturer entity.
func (c *ManufacturerClient) Create() *ManufacturerCreate {
	mutation := newManufacturerMutation(c.config, OpCreate)
	return &ManufacturerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Manufacturer entities.
func (c *ManufacturerClient) CreateBulk(builders ...*ManufacturerCreate) *ManufacturerCreateBulk {
	return &ManufacturerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ManufacturerClient) MapCreateBulk(slice any, setFunc func(*ManufacturerCreate, int)) *ManufacturerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ManufacturerCreateBulk{err: fmt.Errorf("calling to ManufacturerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ManufacturerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ManufacturerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Manufacturer.
func (c *ManufacturerClient) Update() *ManufacturerUpdate {
	mutation := newManufacturerMutation(c.config, OpUpdate)
	return &ManufacturerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ManufacturerClient) UpdateOne(_m *Manufacturer) *ManufacturerUpdateOne {
	mutation := newManufacturerMutation(c.config, OpUpdateOne, withManufacturer(_m))
	return &ManufacturerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ManufacturerClient) UpdateOneID(id uuid.UUID) *ManufacturerUpdateOne {
	mutation := newManufacturerMutation(c.config, OpUpdateOne, withManufacturerID(id))
	return &ManufacturerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Manufacturer.
func (c *ManufacturerClient) Delete() *ManufacturerDelete {
	mutation := newManufacturerMutation(c.config, OpDelete)
	return &ManufacturerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ManufacturerClient) DeleteOne(_m *Manufacturer) *ManufacturerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ManufacturerClient) DeleteOneID(id uuid.UUID) *ManufacturerDeleteOne {
	builder := c.Delete().Where(manufacturer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ManufacturerDeleteOne{builder}
}

// Query returns a query builder for Manufacturer.
func (c *ManufacturerClient) Query() *ManufacturerQuery {
	return &ManufacturerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeManufacturer},
		inters: c.Interceptors(),
	}
}

// Get returns a Manufacturer entity by its id.
func (c *ManufacturerClient) Get(ctx context.Context, id uuid.UUID) (*Manufacturer, error) {
	return c.Query().Where(manufacturer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ManufacturerClient) GetX(ctx context.Context, id uuid.UUID) *Manufacturer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ManufacturerClient) Hooks() []Hook {
	return c.hooks.Manufacturer
}

// Interceptors returns the client interceptors.
func (c *ManufacturerClient) Interceptors() []Interceptor {
	return c.inters.Manufacturer
}

func (c *ManufacturerClient) mutate(ctx context.Context, m *ManufacturerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ManufacturerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ManufacturerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ManufacturerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ManufacturerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Manufacturer mutation op: %q", m.Op())
	}
}

// OfflineSyncRecordClient is a client for the OfflineSyncRecord schema.
type OfflineSyncRecordClient struct {
	config
}

// NewOfflineSyncRecordClient returns a client for the OfflineSyncRecord from the given config.
func NewOfflineSyncRecordClient(c config) *OfflineSyncRecordClient {
	return &OfflineSyncRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `offlinesyncrecord.Hooks(f(g(h())))`.
func (c *OfflineSyncRecordClient) Use(hooks ...Hook) {
	c.hooks.OfflineSyncRecord = append(c.hooks.OfflineSyncRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `offlinesyncrecord.Intercept(f(g(h())))`.
func (c *OfflineSyncRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.OfflineSyncRecord = append(c.inters.OfflineSyncRecord, interceptors...)
}

// Create returns a builder for creating a OfflineSyncRecord entity.
func (c *OfflineSyncRecordClient) Create() *OfflineSyncRecordCreate {
	mutation := newOfflineSyncRecordMutation(c.config, OpCreate)
	return &OfflineSyncRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OfflineSyncRecord entities.
func (c *OfflineSyncRecordClient) CreateBulk(builders ...*OfflineSyncRecordCreate) *OfflineSyncRecordCreateBulk {
	return &OfflineSyncRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OfflineSyncRecordClient) MapCreateBulk(slice any, setFunc func(*OfflineSyncRecordCreate, int)) *OfflineSyncRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OfflineSyncRecordCreateBulk{err: fmt.Errorf("calling to OfflineSyncRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OfflineSyncRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OfflineSyncRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OfflineSyncRecord.
func (c *OfflineSyncRecordClient) Update() *OfflineSyncRecordUpdate {
	mutation := newOfflineSyncRecordMutation(c.config, OpUpdate)
	return &OfflineSyncRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OfflineSyncRecordClient) UpdateOne(_m *OfflineSyncRecord) *OfflineSyncRecordUpdateOne {
	mutation := newOfflineSyncRecordMutation(c.config, OpUpdateOne, withOfflineSyncRecord(_m))
	return &OfflineSyncRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OfflineSyncRecordClient) UpdateOneID(id uuid.UUID) *OfflineSyncRecordUpdateOne {
	mutation := newOfflineSyncRecordMutation(c.config, OpUpdateOne, withOfflineSyncRecordID(id))
	return &OfflineSyncRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OfflineSyncRecord.
func (c *OfflineSyncRecordClient) Delete() *OfflineSyncRecordDelete {
	mutation := newOfflineSyncRecordMutation(c.config, OpDelete)
	return &OfflineSyncRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OfflineSyncRecordClient) DeleteOne(_m *OfflineSyncRecord) *OfflineSyncRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OfflineSyncRecordClient) DeleteOneID(id uuid.UUID) *OfflineSyncRecordDeleteOne {
	builder := c.Delete().Where(offlinesyncrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OfflineSyncRecordDeleteOne{builder}
}

// Query returns a query builder for OfflineSyncRecord.
func (c *OfflineSyncRecordClient) Query() *OfflineSyncRecordQuery {
	return &OfflineSyncRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOfflineSyncRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a OfflineSyncRecord entity by its id.
func (c *OfflineSyncRecordClient) Get(ctx context.Context, id uuid.UUID) (*OfflineSyncRecord, error) {
	return c.Query().Where(offlinesyncrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OfflineSyncRecordClient) GetX(ctx context.Context, id uuid.UUID) *OfflineSyncRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OfflineSyncRecordClient) Hooks() []Hook {
	return c.hooks.OfflineSyncRecord
}

// Interceptors returns the client interceptors.
func (c *OfflineSyncRecordClient) Interceptors() []Interceptor {
	return c.inters.OfflineSyncRecord
}

func (c *OfflineSyncRecordClient) mutate(ctx context.Context, m *OfflineSyncRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OfflineSyncRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OfflineSyncRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OfflineSyncRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OfflineSyncRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OfflineSyncRecord mutation op: %q", m.Op())
	}
}

// ParkingRecordClient is a client for the ParkingRecord schema.
type ParkingRecordClient struct {
	config
}

// NewParkingRecordClient returns a client for the ParkingRecord from the given config.
func NewParkingRecordClient(c config) *ParkingRecordClient {
	return &ParkingRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `parkingrecord.Hooks(f(g(h())))`.
func (c *ParkingRecordClient) Use(hooks ...Hook) {
	c.hooks.ParkingRecord = append(c.hooks.ParkingRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `parkingrecord.Intercept(f(g(h())))`.
func (c *ParkingRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.ParkingRecord = append(c.inters.ParkingRecord, interceptors...)
}

// Create returns a builder for creating a ParkingRecord entity.
func (c *ParkingRecordClient) Create() *ParkingRecordCreate {
	mutation := newParkingRecordMutation(c.config, OpCreate)
	return &ParkingRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ParkingRecord entities.
func (c *ParkingRecordClient) CreateBulk(builders ...*ParkingRecordCreate) *ParkingRecordCreateBulk {
	return &ParkingRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ParkingRecordClient) MapCreateBulk(slice any, setFunc func(*ParkingRecordCreate, int)) *ParkingRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ParkingRecordCreateBulk{err: fmt.Errorf("calling to ParkingRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ParkingRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ParkingRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ParkingRecord.
func (c *ParkingRecordClient) Update() *ParkingRecordUpdate {
	mutation := newParkingRecordMutation(c.config, OpUpdate)
	return &ParkingRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ParkingRecordClient) UpdateOne(_m *ParkingRecord) *ParkingRecordUpdateOne {
	mutation := newParkingRecordMutation(c.config, OpUpdateOne, withParkingRecord(_m))
	return &ParkingRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ParkingRecordClient) UpdateOneID(id uuid.UUID) *ParkingRecordUpdateOne {
	mutation := newParkingRecordMutation(c.config, OpUpdateOne, withParkingRecordID(id))
	return &ParkingRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ParkingRecord.
func (c *ParkingRecordClient) Delete() *ParkingRecordDelete {
	mutation := newParkingRecordMutation(c.config, OpDelete)
	return &ParkingRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ParkingRecordClient) DeleteOne(_m *ParkingRecord) *ParkingRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ParkingRecordClient) DeleteOneID(id uuid.UUID) *ParkingRecordDeleteOne {
	builder := c.Delete().Where(parkingrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ParkingRecordDeleteOne{builder}
}

// Query returns a query builder for ParkingRecord.
func (c *ParkingRecordClient) Query() *ParkingRecordQuery {
	return &ParkingRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeParkingRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a ParkingRecord entity by its id.
func (c *ParkingRecordClient) Get(ctx context.Context, id uuid.UUID) (*ParkingRecord, error) {
	return c.Query().Where(parkingrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ParkingRecordClient) GetX(ctx context.Context, id uuid.UUID) *ParkingRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ParkingRecordClient) Hooks() []Hook {
	return c.hooks.ParkingRecord
}

// Interceptors returns the client interceptors.
func (c *ParkingRecordClient) Interceptors() []Interceptor {
	return c.inters.ParkingRecord
}

func (c *ParkingRecordClient) mutate(ctx context.Context, m *ParkingRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ParkingRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ParkingRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ParkingRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ParkingRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ParkingRecord mutation op: %q", m.Op())
	}
}

// VehicleClient is a client for the Vehicle schema.
type VehicleClient struct {
	config
}

// NewVehicleClient returns a client for the Vehicle from the given config.
func NewVehicleClient(c config) *VehicleClient {
	return &VehicleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `vehicle.Hooks(f(g(h())))`.
func (c *VehicleClient) Use(hooks ...Hook) {
	c.hooks.Vehicle = append(c.hooks.Vehicle, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `vehicle.Intercept(f(g(h())))`.
func (c *VehicleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Vehicle = append(c.inters.Vehicle, interceptors...)
}

// Create returns a builder for creating a Vehicle entity.
func (c *VehicleClient) Create() *VehicleCreate {
	mutation := newVehicleMutation(c.config, OpCreate)
	return &VehicleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Vehicle entities.
func (c *VehicleClient) CreateBulk(builders ...*VehicleCreate) *VehicleCreateBulk {
	return &VehicleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *VehicleClient) MapCreateBulk(slice any, setFunc func(*VehicleCreate, int)) *VehicleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &VehicleCreateBulk{err: fmt.Errorf("calling to VehicleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*VehicleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &VehicleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Vehicle.
func (c *VehicleClient) Update() *VehicleUpdate {
	mutation := newVehicleMutation(c.config, OpUpdate)
	return &VehicleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VehicleClient) UpdateOne(_m *Vehicle) *VehicleUpdateOne {
	mutation := newVehicleMutation(c.config, OpUpdateOne, withVehicle(_m))
	return &VehicleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VehicleClient) UpdateOneID(id uuid.UUID) *VehicleUpdateOne {
	mutation := newVehicleMutation(c.config, OpUpdateOne, withVehicleID(id))
	return &VehicleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Vehicle.
func (c *VehicleClient) Delete() *VehicleDelete {
	mutation := newVehicleMutation(c.config, OpDelete)
	return &VehicleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *VehicleClient) DeleteOne(_m *Vehicle) *VehicleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *VehicleClient) DeleteOneID(id uuid.UUID) *VehicleDeleteOne {
	builder := c.Delete().Where(vehicle.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VehicleDeleteOne{builder}
}

// Query returns a query builder for Vehicle.
func (c *VehicleClient) Query() *VehicleQuery {
	return &VehicleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeVehicle},
		inters: c.Interceptors(),
	}
}

// Get returns a Vehicle entity by its id.
func (c *VehicleClient) Get(ctx context.Context, id uuid.UUID) (*Vehicle, error) {
	return c.Query().Where(vehicle.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VehicleClient) GetX(ctx context.Context, id uuid.UUID) *Vehicle {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *VehicleClient) Hooks() []Hook {
	return c.hooks.Vehicle
}

// Interceptors returns the client interceptors.
func (c *VehicleClient) Interceptors() []Interceptor {
	return c.inters.Vehicle
}

func (c *VehicleClient) mutate(ctx context.Context, m *VehicleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&VehicleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&VehicleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&VehicleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&VehicleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Vehicle mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BillingRule, Device, DeviceFault, DeviceLog, DevicePerformance, DeviceUpgrade,
		Firmware, Lane, Manufacturer, OfflineSyncRecord, ParkingRecord,
		Vehicle []ent.Hook
	}
	inters struct {
		BillingRule, Device, DeviceFault, DeviceLog, DevicePerformance, DeviceUpgrade,
		Firmware, Lane, Manufacturer, OfflineSyncRecord, ParkingRecord,
		Vehicle []ent.Interceptor
	}
)
