// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/devicelog"
)

// DeviceLogCreate is the builder for creating a DeviceLog entity.
type DeviceLogCreate struct {
	config
	mutation *DeviceLogMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *DeviceLogCreate) SetDeviceID(v string) *DeviceLogCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetLogType sets the "log_type" field.
func (_c *DeviceLogCreate) SetLogType(v devicelog.LogType) *DeviceLogCreate {
	_c.mutation.SetLogType(v)
	return _c
}

// SetNillableLogType sets the "log_type" field if the given value is not nil.
func (_c *DeviceLogCreate) SetNillableLogType(v *devicelog.LogType) *DeviceLogCreate {
	if v != nil {
		_c.SetLogType(*v)
	}
	return _c
}

// SetLogLevel sets the "log_level" field.
func (_c *DeviceLogCreate) SetLogLevel(v string) *DeviceLogCreate {
	_c.mutation.SetLogLevel(v)
	return _c
}

// SetNillableLogLevel sets the "log_level" field if the given value is not nil.
func (_c *DeviceLogCreate) SetNillableLogLevel(v *string) *DeviceLogCreate {
	if v != nil {
		_c.SetLogLevel(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *DeviceLogCreate) SetMessage(v string) *DeviceLogCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetFaultCode sets the "fault_code" field.
func (_c *DeviceLogCreate) SetFaultCode(v string) *DeviceLogCreate {
	_c.mutation.SetFaultCode(v)
	return _c
}

// SetNillableFaultCode sets the "fault_code" field if the given value is not nil.
func (_c *DeviceLogCreate) SetNillableFaultCode(v *string) *DeviceLogCreate {
	if v != nil {
		_c.SetFaultCode(*v)
	}
	return _c
}

// SetDetails sets the "details" field.
func (_c *DeviceLogCreate) SetDetails(v map[string]interface{}) *DeviceLogCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceLogCreate) SetCreatedAt(v time.Time) *DeviceLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceLogCreate) SetNillableCreatedAt(v *time.Time) *DeviceLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceLogCreate) SetID(v uuid.UUID) *DeviceLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DeviceLogCreate) SetNillableID(v *uuid.UUID) *DeviceLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DeviceLogMutation object of the builder.
func (_c *DeviceLogCreate) Mutation() *DeviceLogMutation {
	return _c.mutation
}

// Save creates the DeviceLog in the database.
func (_c *DeviceLogCreate) Save(ctx context.Context) (*DeviceLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceLogCreate) SaveX(ctx context.Context) *DeviceLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceLogCreate) defaults() {
	if _, ok := _c.mutation.LogType(); !ok {
		v := devicelog.DefaultLogType
		_c.mutation.SetLogType(v)
	}
	if _, ok := _c.mutation.LogLevel(); !ok {
		v := devicelog.DefaultLogLevel
		_c.mutation.SetLogLevel(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := devicelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := devicelog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceLogCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "DeviceLog.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := devicelog.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DeviceLog.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LogType(); !ok {
		return &ValidationError{Name: "log_type", err: errors.New(`ent: missing required field "DeviceLog.log_type"`)}
	}
	if v, ok := _c.mutation.LogType(); ok {
		if err := devicelog.LogTypeValidator(v); err != nil {
			return &ValidationError{Name: "log_type", err: fmt.Errorf(`ent: validator failed for field "DeviceLog.log_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LogLevel(); !ok {
		return &ValidationError{Name: "log_level", err: errors.New(`ent: missing required field "DeviceLog.log_level"`)}
	}
	if v, ok := _c.mutation.LogLevel(); ok {
		if err := devicelog.LogLevelValidator(v); err != nil {
			return &ValidationError{Name: "log_level", err: fmt.Errorf(`ent: validator failed for field "DeviceLog.log_level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "DeviceLog.message"`)}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := devicelog.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "DeviceLog.message": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FaultCode(); ok {
		if err := devicelog.FaultCodeValidator(v); err != nil {
			return &ValidationError{Name: "fault_code", err: fmt.Errorf(`ent: validator failed for field "DeviceLog.fault_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceLog.created_at"`)}
	}
	return nil
}

func (_c *DeviceLogCreate) sqlSave(ctx context.Context) (*DeviceLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceLogCreate) createSpec() (*DeviceLog, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(devicelog.Table, sqlgraph.NewFieldSpec(devicelog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(devicelog.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.LogType(); ok {
		_spec.SetField(devicelog.FieldLogType, field.TypeEnum, value)
		_node.LogType = value
	}
	if value, ok := _c.mutation.LogLevel(); ok {
		_spec.SetField(devicelog.FieldLogLevel, field.TypeString, value)
		_node.LogLevel = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(devicelog.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.FaultCode(); ok {
		_spec.SetField(devicelog.FieldFaultCode, field.TypeString, value)
		_node.FaultCode = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(devicelog.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(devicelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DeviceLogCreateBulk is the builder for creating many DeviceLog entities in bulk.
type DeviceLogCreateBulk struct {
	config
	err      error
	builders []*DeviceLogCreate
}

// Save creates the DeviceLog entities in the database.
func (_c *DeviceLogCreateBulk) Save(ctx context.Context) ([]*DeviceLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceLogCreateBulk) SaveX(ctx context.Context) []*DeviceLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
