// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/offlinesyncrecord"
)

// OfflineSyncRecordCreate is the builder for creating a OfflineSyncRecord entity.
type OfflineSyncRecordCreate struct {
	config
	mutation *OfflineSyncRecordMutation
	hooks    []Hook
}

// SetOfflineID sets the "offline_id" field.
func (_c *OfflineSyncRecordCreate) SetOfflineID(v string) *OfflineSyncRecordCreate {
	_c.mutation.SetOfflineID(v)
	return _c
}

// SetRecordID sets the "record_id" field.
func (_c *OfflineSyncRecordCreate) SetRecordID(v uuid.UUID) *OfflineSyncRecordCreate {
	_c.mutation.SetRecordID(v)
	return _c
}

// SetNillableRecordID sets the "record_id" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableRecordID(v *uuid.UUID) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetRecordID(*v)
	}
	return _c
}

// SetLotID sets the "lot_id" field.
func (_c *OfflineSyncRecordCreate) SetLotID(v uuid.UUID) *OfflineSyncRecordCreate {
	_c.mutation.SetLotID(v)
	return _c
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableLotID(v *uuid.UUID) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetLotID(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *OfflineSyncRecordCreate) SetDeviceID(v string) *OfflineSyncRecordCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetGateID sets the "gate_id" field.
func (_c *OfflineSyncRecordCreate) SetGateID(v string) *OfflineSyncRecordCreate {
	_c.mutation.SetGateID(v)
	return _c
}

// SetOpenTime sets the "open_time" field.
func (_c *OfflineSyncRecordCreate) SetOpenTime(v time.Time) *OfflineSyncRecordCreate {
	_c.mutation.SetOpenTime(v)
	return _c
}

// SetSyncAmount sets the "sync_amount" field.
func (_c *OfflineSyncRecordCreate) SetSyncAmount(v float64) *OfflineSyncRecordCreate {
	_c.mutation.SetSyncAmount(v)
	return _c
}

// SetNillableSyncAmount sets the "sync_amount" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableSyncAmount(v *float64) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetSyncAmount(*v)
	}
	return _c
}

// SetSyncStatus sets the "sync_status" field.
func (_c *OfflineSyncRecordCreate) SetSyncStatus(v offlinesyncrecord.SyncStatus) *OfflineSyncRecordCreate {
	_c.mutation.SetSyncStatus(v)
	return _c
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableSyncStatus(v *offlinesyncrecord.SyncStatus) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetSyncStatus(*v)
	}
	return _c
}

// SetSyncError sets the "sync_error" field.
func (_c *OfflineSyncRecordCreate) SetSyncError(v string) *OfflineSyncRecordCreate {
	_c.mutation.SetSyncError(v)
	return _c
}

// SetNillableSyncError sets the "sync_error" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableSyncError(v *string) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetSyncError(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *OfflineSyncRecordCreate) SetRetryCount(v int) *OfflineSyncRecordCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableRetryCount(v *int) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *OfflineSyncRecordCreate) SetSyncedAt(v time.Time) *OfflineSyncRecordCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableSyncedAt(v *time.Time) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OfflineSyncRecordCreate) SetCreatedAt(v time.Time) *OfflineSyncRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableCreatedAt(v *time.Time) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OfflineSyncRecordCreate) SetID(v uuid.UUID) *OfflineSyncRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OfflineSyncRecordCreate) SetNillableID(v *uuid.UUID) *OfflineSyncRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OfflineSyncRecordMutation object of the builder.
func (_c *OfflineSyncRecordCreate) Mutation() *OfflineSyncRecordMutation {
	return _c.mutation
}

// Save creates the OfflineSyncRecord in the database.
func (_c *OfflineSyncRecordCreate) Save(ctx context.Context) (*OfflineSyncRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OfflineSyncRecordCreate) SaveX(ctx context.Context) *OfflineSyncRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OfflineSyncRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OfflineSyncRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OfflineSyncRecordCreate) defaults() {
	if _, ok := _c.mutation.SyncStatus(); !ok {
		v := offlinesyncrecord.DefaultSyncStatus
		_c.mutation.SetSyncStatus(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := offlinesyncrecord.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := offlinesyncrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := offlinesyncrecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OfflineSyncRecordCreate) check() error {
	if _, ok := _c.mutation.OfflineID(); !ok {
		return &ValidationError{Name: "offline_id", err: errors.New(`ent: missing required field "OfflineSyncRecord.offline_id"`)}
	}
	if v, ok := _c.mutation.OfflineID(); ok {
		if err := offlinesyncrecord.OfflineIDValidator(v); err != nil {
			return &ValidationError{Name: "offline_id", err: fmt.Errorf(`ent: validator failed for field "OfflineSyncRecord.offline_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "OfflineSyncRecord.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := offlinesyncrecord.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "OfflineSyncRecord.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GateID(); !ok {
		return &ValidationError{Name: "gate_id", err: errors.New(`ent: missing required field "OfflineSyncRecord.gate_id"`)}
	}
	if v, ok := _c.mutation.GateID(); ok {
		if err := offlinesyncrecord.GateIDValidator(v); err != nil {
			return &ValidationError{Name: "gate_id", err: fmt.Errorf(`ent: validator failed for field "OfflineSyncRecord.gate_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpenTime(); !ok {
		return &ValidationError{Name: "open_time", err: errors.New(`ent: missing required field "OfflineSyncRecord.open_time"`)}
	}
	if _, ok := _c.mutation.SyncStatus(); !ok {
		return &ValidationError{Name: "sync_status", err: errors.New(`ent: missing required field "OfflineSyncRecord.sync_status"`)}
	}
	if v, ok := _c.mutation.SyncStatus(); ok {
		if err := offlinesyncrecord.SyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "sync_status", err: fmt.Errorf(`ent: validator failed for field "OfflineSyncRecord.sync_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "OfflineSyncRecord.retry_count"`)}
	}
	if v, ok := _c.mutation.RetryCount(); ok {
		if err := offlinesyncrecord.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "OfflineSyncRecord.retry_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OfflineSyncRecord.created_at"`)}
	}
	return nil
}

func (_c *OfflineSyncRecordCreate) sqlSave(ctx context.Context) (*OfflineSyncRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OfflineSyncRecordCreate) createSpec() (*OfflineSyncRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &OfflineSyncRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(offlinesyncrecord.Table, sqlgraph.NewFieldSpec(offlinesyncrecord.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OfflineID(); ok {
		_spec.SetField(offlinesyncrecord.FieldOfflineID, field.TypeString, value)
		_node.OfflineID = value
	}
	if value, ok := _c.mutation.RecordID(); ok {
		_spec.SetField(offlinesyncrecord.FieldRecordID, field.TypeUUID, value)
		_node.RecordID = &value
	}
	if value, ok := _c.mutation.LotID(); ok {
		_spec.SetField(offlinesyncrecord.FieldLotID, field.TypeUUID, value)
		_node.LotID = &value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(offlinesyncrecord.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.GateID(); ok {
		_spec.SetField(offlinesyncrecord.FieldGateID, field.TypeString, value)
		_node.GateID = value
	}
	if value, ok := _c.mutation.OpenTime(); ok {
		_spec.SetField(offlinesyncrecord.FieldOpenTime, field.TypeTime, value)
		_node.OpenTime = value
	}
	if value, ok := _c.mutation.SyncAmount(); ok {
		_spec.SetField(offlinesyncrecord.FieldSyncAmount, field.TypeFloat64, value)
		_node.SyncAmount = value
	}
	if value, ok := _c.mutation.SyncStatus(); ok {
		_spec.SetField(offlinesyncrecord.FieldSyncStatus, field.TypeEnum, value)
		_node.SyncStatus = value
	}
	if value, ok := _c.mutation.SyncError(); ok {
		_spec.SetField(offlinesyncrecord.FieldSyncError, field.TypeString, value)
		_node.SyncError = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(offlinesyncrecord.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(offlinesyncrecord.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(offlinesyncrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OfflineSyncRecordCreateBulk is the builder for creating many OfflineSyncRecord entities in bulk.
type OfflineSyncRecordCreateBulk struct {
	config
	err      error
	builders []*OfflineSyncRecordCreate
}

// Save creates the OfflineSyncRecord entities in the database.
func (_c *OfflineSyncRecordCreateBulk) Save(ctx context.Context) ([]*OfflineSyncRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OfflineSyncRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OfflineSyncRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OfflineSyncRecordCreateBulk) SaveX(ctx context.Context) []*OfflineSyncRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OfflineSyncRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OfflineSyncRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
