// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/parkingspace"
	"github.com/xuanyiying/smart-park/internal/vehicle/data/ent/predicate"
)

// ParkingSpaceDelete is the builder for deleting a ParkingSpace entity.
type ParkingSpaceDelete struct {
	config
	hooks    []Hook
	mutation *ParkingSpaceMutation
}

// Where appends a list predicates to the ParkingSpaceDelete builder.
func (_d *ParkingSpaceDelete) Where(ps ...predicate.ParkingSpace) *ParkingSpaceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ParkingSpaceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ParkingSpaceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ParkingSpaceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(parkingspace.Table, sqlgraph.NewFieldSpec(parkingspace.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ParkingSpaceDeleteOne is the builder for deleting a single ParkingSpace entity.
type ParkingSpaceDeleteOne struct {
	_d *ParkingSpaceDelete
}

// Where appends a list predicates to the ParkingSpaceDelete builder.
func (_d *ParkingSpaceDeleteOne) Where(ps ...predicate.ParkingSpace) *ParkingSpaceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ParkingSpaceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{parkingspace.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ParkingSpaceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
