// Code generated by ent, DO NOT EDIT.

package firmwareupdate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/xuanyiying/smart-park/internal/device/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldID, id))
}

// UpdateID applies equality check predicate on the "update_id" field. It's identical to UpdateIDEQ.
func UpdateID(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldUpdateID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldDeviceID, v))
}

// FirmwareVersion applies equality check predicate on the "firmware_version" field. It's identical to FirmwareVersionEQ.
func FirmwareVersion(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldFirmwareVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldStatus, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldProgress, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldErrorMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldCompletedAt, v))
}

// UpdateIDEQ applies the EQ predicate on the "update_id" field.
func UpdateIDEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldUpdateID, v))
}

// UpdateIDNEQ applies the NEQ predicate on the "update_id" field.
func UpdateIDNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldUpdateID, v))
}

// UpdateIDIn applies the In predicate on the "update_id" field.
func UpdateIDIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldUpdateID, vs...))
}

// UpdateIDNotIn applies the NotIn predicate on the "update_id" field.
func UpdateIDNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldUpdateID, vs...))
}

// UpdateIDGT applies the GT predicate on the "update_id" field.
func UpdateIDGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldUpdateID, v))
}

// UpdateIDGTE applies the GTE predicate on the "update_id" field.
func UpdateIDGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldUpdateID, v))
}

// UpdateIDLT applies the LT predicate on the "update_id" field.
func UpdateIDLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldUpdateID, v))
}

// UpdateIDLTE applies the LTE predicate on the "update_id" field.
func UpdateIDLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldUpdateID, v))
}

// UpdateIDContains applies the Contains predicate on the "update_id" field.
func UpdateIDContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldUpdateID, v))
}

// UpdateIDHasPrefix applies the HasPrefix predicate on the "update_id" field.
func UpdateIDHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldUpdateID, v))
}

// UpdateIDHasSuffix applies the HasSuffix predicate on the "update_id" field.
func UpdateIDHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldUpdateID, v))
}

// UpdateIDEqualFold applies the EqualFold predicate on the "update_id" field.
func UpdateIDEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldUpdateID, v))
}

// UpdateIDContainsFold applies the ContainsFold predicate on the "update_id" field.
func UpdateIDContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldUpdateID, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldDeviceID, v))
}

// FirmwareVersionEQ applies the EQ predicate on the "firmware_version" field.
func FirmwareVersionEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldFirmwareVersion, v))
}

// FirmwareVersionNEQ applies the NEQ predicate on the "firmware_version" field.
func FirmwareVersionNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldFirmwareVersion, v))
}

// FirmwareVersionIn applies the In predicate on the "firmware_version" field.
func FirmwareVersionIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldFirmwareVersion, vs...))
}

// FirmwareVersionNotIn applies the NotIn predicate on the "firmware_version" field.
func FirmwareVersionNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldFirmwareVersion, vs...))
}

// FirmwareVersionGT applies the GT predicate on the "firmware_version" field.
func FirmwareVersionGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldFirmwareVersion, v))
}

// FirmwareVersionGTE applies the GTE predicate on the "firmware_version" field.
func FirmwareVersionGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldFirmwareVersion, v))
}

// FirmwareVersionLT applies the LT predicate on the "firmware_version" field.
func FirmwareVersionLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldFirmwareVersion, v))
}

// FirmwareVersionLTE applies the LTE predicate on the "firmware_version" field.
func FirmwareVersionLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldFirmwareVersion, v))
}

// FirmwareVersionContains applies the Contains predicate on the "firmware_version" field.
func FirmwareVersionContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldFirmwareVersion, v))
}

// FirmwareVersionHasPrefix applies the HasPrefix predicate on the "firmware_version" field.
func FirmwareVersionHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldFirmwareVersion, v))
}

// FirmwareVersionHasSuffix applies the HasSuffix predicate on the "firmware_version" field.
func FirmwareVersionHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldFirmwareVersion, v))
}

// FirmwareVersionEqualFold applies the EqualFold predicate on the "firmware_version" field.
func FirmwareVersionEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldFirmwareVersion, v))
}

// FirmwareVersionContainsFold applies the ContainsFold predicate on the "firmware_version" field.
func FirmwareVersionContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldFirmwareVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldStatus, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldProgress, v))
}

// ProgressContains applies the Contains predicate on the "progress" field.
func ProgressContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldProgress, v))
}

// ProgressHasPrefix applies the HasPrefix predicate on the "progress" field.
func ProgressHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldProgress, v))
}

// ProgressHasSuffix applies the HasSuffix predicate on the "progress" field.
func ProgressHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldProgress, v))
}

// ProgressEqualFold applies the EqualFold predicate on the "progress" field.
func ProgressEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldProgress, v))
}

// ProgressContainsFold applies the ContainsFold predicate on the "progress" field.
func ProgressContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldProgress, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FirmwareUpdate) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FirmwareUpdate) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FirmwareUpdate) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.NotPredicates(p))
}
