// Code generated by ent, DO NOT EDIT.

package parkinglot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/xuanyiying/smart-park/internal/admin/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldName, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldAddress, v))
}

// Lanes applies equality check predicate on the "lanes" field. It's identical to LanesEQ.
func Lanes(v int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldLanes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldContainsFold(FieldName, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldContainsFold(FieldAddress, v))
}

// LanesEQ applies the EQ predicate on the "lanes" field.
func LanesEQ(v int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldLanes, v))
}

// LanesNEQ applies the NEQ predicate on the "lanes" field.
func LanesNEQ(v int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNEQ(FieldLanes, v))
}

// LanesIn applies the In predicate on the "lanes" field.
func LanesIn(vs ...int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldIn(FieldLanes, vs...))
}

// LanesNotIn applies the NotIn predicate on the "lanes" field.
func LanesNotIn(vs ...int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNotIn(FieldLanes, vs...))
}

// LanesGT applies the GT predicate on the "lanes" field.
func LanesGT(v int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGT(FieldLanes, v))
}

// LanesGTE applies the GTE predicate on the "lanes" field.
func LanesGTE(v int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGTE(FieldLanes, v))
}

// LanesLT applies the LT predicate on the "lanes" field.
func LanesLT(v int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLT(FieldLanes, v))
}

// LanesLTE applies the LTE predicate on the "lanes" field.
func LanesLTE(v int) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLTE(FieldLanes, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ParkingLot {
	return predicate.ParkingLot(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ParkingLot) predicate.ParkingLot {
	return predicate.ParkingLot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ParkingLot) predicate.ParkingLot {
	return predicate.ParkingLot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ParkingLot) predicate.ParkingLot {
	return predicate.ParkingLot(sql.NotPredicates(p))
}
